[quote.epigraph, , Prov. 31:30]
____
Charm is deceitful, and beauty is passing, but a woman that fears the Lord,
she shall be praised.
____

== The Life of Elizabeth Stirredge

The Lord has been pleased to count me worthy to travel in Zion`'s
way--a way I have found to be straight and narrow.
Oh, so many who have been called, and some who have entered into it,
have gone into bypaths and crooked ways again;
but I have found the blessed effect of keeping in the right way.
I therefore have a great concern upon my spirit for my children,
who are coming up after me, that they may not be forgetful of keeping in the right way,
after the Lord shall be pleased to take me from them.
It is in my heart, as my heavenly Father will be pleased to assist me,
to leave a short testimony behind me for my children of some occurrences of my life,
and of the goodness of the Lord to me all my life long, even unto this very day.
Indeed, He is worthy forever to be held in remembrance;
and He shall have the praise of His own work forever.

I was born in 1634 at Thornbury, in Gloucestershire, of honest parents.
My father`'s name was William Tayler, and my parents were people fearing God,
and very zealous in their day.
My father being one of those called Puritans,
prophesied of Friends many years before they came.
He said, "`There is a day coming wherein truth will gloriously break forth,
more gloriously than ever since the apostles`' days, but I shall not live to see it.`"
He died in the faith of it seven years before Friends came.
His honest and chaste life is often in my remembrance,
and his fervent and zealous prayers amongst his family are not forgotten by me.

My parents brought me up after a very strict manner,
so that I was much a stranger to the world and its ways.
In my tender years I was of a sad heart,
and much concerned with inward fear over what would become of me when I should die.
Whenever it was my lot to be near any who would talk rudely, or swear,
or be overcome with strong drink, I dreaded to pass by them.
When I heard it thunder, oh, the dread and terror that would fall upon me!
I would get to the most private place that I could to mourn in secret,
thinking the Lord would render vengeance upon the heads of the wicked.
When I saw the flashes of lightning, "`Oh!`" thought I,
"`Where shall I go to hide myself from the wrath of the dreadful and
terrible God?`" Thus was I possessed with a concern for my soul;
and before I was ten years of age,
I was so filled with fears and doubts that I
could take no delight in anything of this world.

When I grew up to riper years, I went to hear those accounted the best men,
who lived up to what was made known to them.
I delighted to hear them, and to be in the company of those who talked of good things,
and discoursed of Scripture, of God and Christ, and of heaven`'s glory.
Oh, how delightful it was to me!
But still I was not satisfied,
for I found I was not a living witness of the states and
conditions which the people of God were in in former days;
and how to attain this I did not know.
Then did I mourn, and say in my heart, "`Oh,
that I had been born in the days when the Lord spoke to Moses,
and to the children of Israel,
and with a high and wonderful power brought forth His people out of Egypt,
through the Red Sea, that I might have known how to walk in the right way,
and to do what the Lord required of me,
and been in acquaintance and familiarity with my Maker!
Then I might have known when I pleased or displeased the Lord, whom my soul loved,
but now I do not know how to become acquainted with Him.`"
What would I not have parted with for the enjoyment of the Lord,
and the assurance of salvation? Surely if it were
possible for me to have enjoyed all the world,
I could freely have parted with it for the peace and satisfaction of
my poor distressed soul that mourned as without hope.
Many a time, and many hours have I spent alone, reading and mourning, when no eye saw me,
nor ear heard me.
But I could find no comfort in reading, because the Bible was a book sealed unto me.
Then did I mourn and say, "`Oh,
that I had been born in the days when our blessed Savior Jesus Christ was upon the earth!
How I would have followed Him and sat at His feet, even as Mary did!
How freely could I have left my father`'s house, and all my relations,
for true peace and assurance of life eternal for my immortal soul!`"

Under this exercise I grew very sad,
insomuch that my mother apprehended I was wasting away, and greatly feared my death.
She would say to me,
"`Can you take delight in nothing? Can you not walk forth into
the fields with the young people for recreation,
and delight yourself in something?`" So to please her,
I did sometimes go forth with sober young people when we had finished our work,
but I found no comfort in that.
I then fell into a custom of reading the Scriptures alone in private,
reading and crying because I knew not the heavenly power and Spirit to have
dominion in me which was in those who gave forth the Scriptures;
and nothing else but the Substance would give me true satisfaction.

Then I fell down upon my knees to pray unto the Lord,
with my heart full of sorrow and tears running down my face,
but I could not utter one word.
This seemed very strange to me,
and set me to thinking that there was none like me in all the world.
This was the enemy`'s work to persuade me there was none like me,
and that because I could not pray in words (as others could),
and was under these afflictions, therefore the Lord had no regard for me.
But the enemy is a liar, for the Lord was near me in every exercise,
and broke my heart and melted my spirit, or else it would not have been so with me.
Oh, my soul can now behold His goodness, for He was near me,
though I was not aware of it, and thought none were as miserable as I.

The enemy endeavored to cast me down and make me despair,
and truly it was the great mercy of the Lord that preserved me from it,
for my affliction was great, and my distresses very many.
The serpent followed me with his temptations,
and I lacked the right understanding as to where my strength was to be found.
I should have stood still and waited upon the living God for strength to overcome him.
But instead of doing so,
the enemy disturbed me and followed me with his subtle allurements--
sometimes to draw my mind into the vanities of this world,
and to a delight in decking myself with fine clothes
that I might appear beautiful in the eyes of the world.
"`For,`" said the enemy,
"`This sadness and trouble that you are under will result to no advantage or comfort,
nor will you be in any esteem amongst your neighbors; therefore,
take your pleasure and be at rest.`"
A liar he is, and ever was from the beginning.
Believe him not, my dear children,
whenever it is your lot to be under temptations or exercises of any kind,
or whatever way the Lord may be pleased to lead
you for the trial of your faith and patience.
The enemy will betray as many as he can; therefore look unto the Lord,
and keep Him in your remembrance, and pray unto Him in your minds,
though you cannot utter one word.
Know assuredly that He is near to help His afflicted children at all times.

Oh, that I had known this in the days of my ignorance, in my young and tender years,
when the Lord was at work in my heart and I knew it not.
For lack of understanding, the enemy betrayed me and led me aside.
I hearkened to him and to the young people who were my neighbors,
and was persuaded that the world had much that would be of great benefit to me.
Upon the death of my father, I was left with hardly a friend,
and in my distress and afflictions was willing to seek a little rest and comfort.
I then lent an ear to the enemy of my soul, and let my mind go forth after fine clothes.
And when my mind was drawn out, I found it knew no limits;
for even when I decked myself as finely as I could, it would hardly give me content.
And when I had one new thing, and then saw another, or a third,
I was as desirous of it as for the former, and so was always unsatisfied.
The lying enemy had promised me rest and peace, but could not give it.
A liar he is and ever was, and my soul is at enmity with him.
May the Lord preserve me and my house out of his snares forever.

But though he had thus drawn out my mind, the Lord did not leave me.
For many times I felt concern about my condition and what would become of me.
And if at any time I was drawn into levity or laughter,
I would feel something smite my heart and bring great heaviness over my spirit.
And as soon as the enemy had drawn my mind into pride,
and to take delight in fine clothes, I found these things became my burden.
I knew not what it was that reproved me,
and I little thought it was the Lord (who is ever good and gracious, kind,
merciful and slow to anger,
and not willing people should run into destruction). I
did not think the Lord looked so closely at my ways,
but since then the Lord has been pleased to open my eyes,
and I can look back and admire His goodness.
Blessed be His worthy name, and the right arm of His strength,
for He early became my guide,
and kept me in great degree from running into the evils
of the world which greatly attend young people.
Yes, He took me by the hand, and led me even in my tender years when I knew it not.

A little time after this, in the year 1654,
the Lord (in the riches of His love) was pleased to prepare
and send forth His faithful servants and laborers,
whose work He greatly prospered--two men of worthy memory,
dear John Audland and John Camm.
When I heard the report of them, it struck a dread over my heart.
Hearing of their plainness, I began to think,
"`How shall I demean myself to go to hear them?`" But a short time after,
a meeting was appointed by them where it was my lot to be.
When I came into the meeting, dear John Audland was preaching.
As soon as I heard his voice, it pierced me; and when I listened to his testimony,
and beheld his solid countenance, oh how my heart was troubled within me!
I knew not what would become of me.

After the meeting was over, I separated myself from my company,
and travelled alone two miles so that no ear
should hear me make my complaint to the Lord.
In bitterness of spirit, I cried, "`Lord,
what shall I do to be saved? I would do anything for the assurance of everlasting life.
And if You will be pleased to accept me upon any terms,
I care not what becomes of this body--even if I must find a
cave in which to mourn out the remainder of my days in sorrow,
and see man no more.`"
But it pleased the Lord to open the eyes of my understanding,
and to lead me by a way that I knew not.
He began the first day`'s work in my heart, which was,
"`The Spirit of the Lord moving upon the face of the
waters,`" and "`dividing the light from the darkness.`"
And when this separation was made, I could see my way in the light,
which was the "`Light unto David`'s feet,
and the lamp unto his paths,`" which light will order everyone`'s way aright,
if they take heed unto it.

It would be too tedious to go through every particular state,
but my earnest cries were to the Lord to lead me in the right way,
and to create in me a new heart, and renew a right spirit within me.
I said, "`Let me be unto You whatever I am, O Lord, and not unto man.
I do not take care for this outward body, but redeem my soul from death,
out of this horrible pit wherein I am held as in chains of darkness.
For if You, in infinite mercy, do not bow Your ear unto my cry and have compassion on me,
I shall perish forever, for I can do nothing else.`"
I can truly say, "`My heart was filled with sorrow, my sighing came before I ate,
and my tears were as my loathsome food.`"
When I lay down, it was in sorrow;
I watered my pillow with my tears before I could take my rest: and when I awoke,
it was with the dread of the Lord over my heart.

Oh, my soul can do no less than magnify the living God who is worthy of praise, honor,
renown, thanksgiving, and obedience forevermore.
And why so? Because He has condescended to the low estate of His handmaid,
and bowed His ear to my prayers, and had regard unto my cries.
Yes, He has answered my request, and given me my heart`'s desire,
which was to be led in the right way.
Zion`'s poor travelers know very well that this is a beginning, or a step in the way,
and I can truly say,
that I never coveted heaven`'s glory more than I
desired to walk in the way that leads thereto.
I then truly believed that the Lord would redeem a people out of the world,
its ways and customs, language, marriage, and burying, and all the world`'s hypocrisy.
Indeed, I looked for this change before I saw any appearance of it.
But my fear was that I should not live to see it,
for the enemy always followed me with his temptations, to work me into unbelief,
and to cast me down into desperation.
Oh, my soul cannot but give the Lord God the glory, the honor, and the renown,
for He is worthy of it forever and evermore.

And now my dear children, this is for you to remember and to keep close to you,
that you may always know the way to heaven`'s glory,
and to enjoy true peace and satisfaction.
Oh, it is a straight and narrow way, and whoever thinks it is not is mistaken.
Keep to the daily cross all the days of your lives, and to truth`'s language;
and more especially, "`Keep your heart with all diligence,
for out of it are the issues of life.`"
Then you will be brought nearer unto the Lord, and grow into acquaintance with Him.
This is what my soul mourned after in the days of my tender years,
which mourning I cannot forget, and I hope never shall,
for I find the good effects of it from day to day.
Indeed it bows my spirit and humbles my heart,
keeping me in a living remembrance of what the Lord has done for me--
though He has been pleased to give me a bitter cup to drink,
and to feed me with the bread of affliction,
and allow temptation upon temptation to come near me.

For the enemy, the subtle serpent, the old dragon,
who was more subtle than all the beasts of the field, followed me with his lies,
to persuade me that the Lord had no regard for me; for if He had,
He would not afflict me so.
"`There is none like you,`" said the wicked one, "`Look abroad,
and see if you can find one whose sorrows are like unto yours.`"
Then would I wander alone in some remote place, where no eye could see me,
nor ear hear me, to make my cry unto the Lord,
who has sweetly comforted me and refreshed my spirit many a time,
and kept my head above the waters.
Blessed be the worthy name of the Lord my God, and the right arm of His strength,
which has wrought wonderfully for my deliverance.
And cursed is the old dragon, who has ever envied man`'s prosperity.
For he endeavored to destroy the blessed work of the Lord (as much as
in his power lay) even after the Lord had done much for me,
and had in a good measure redeemed my soul from death
by a high hand and an out-stretched arm--yes,
even after He had brought me out of Egypt`'s darkness, and through the Red Sea,
where my soul had true cause to sing praises
unto the most high God who lives forevermore.
Oh, let me never forget this great and wonderful deliverance,
but instead keep down in that which bows my heart from day to day,
and humbles my spirit before the Lord.
He has been pleased to do more for me than my tongue is able to declare.
And although I can say my eyes have seen afflictions,
and that no affliction seems joyous at present, but rather grievous,
yet afterwards it brings the peaceable fruits of righteousness.

And now, my dear children,
my aim is to make you a little acquainted with the work of the Lord in my heart,
and also with the subtle devices and contrivances of the enemy of your immortal souls.
His way is to set his baits according to an individual`'s nature,
for therein he is most likely to prevail.
And because I was of a sad heart, and very subject to be cast down, he therefore,
with all his might, did endeavor to cast me into despair and unbelief,
persuading me I should never hold out to the end.
Then I would pray to the Lord to preserve me to the end,
for my affliction was very great, both inward and outward.
But the enemy cast many things before me which seemed too hard for me to go through.
And when my mind was sorrowful, he took ground in me, and filled me with imaginations,
until my heart grew hard before I was aware,
and I had lost that sweet enjoyment and heavenly fellowship with which I was comforted.
And when the enemy had gotten a little ground,
he set his baits so agreeably to my nature,
that when I had any remembrance of the condition I was in before (and now
for a little time had lost) I had great cause to mourn to the Lord,
who was able to deliver me, as He had done many times.

Yet the enemy prevailed upon me a little further,
even as I was making my complaint to the Lord, saying in my heart,
"`There is no sorrow like mine`"--for I had lost my Beloved, and my loss was great.
This mourning was very suitable to my condition,
but the subtle serpent persuaded me that I was discontented, a murmurer and complainer,
and that I made the Lord weary with my crying.
Then I believed I should be shut out of His kingdom,
for I knew it was the murmurers and complainers who perished in the wilderness.
So I was caught by his subtlety, and convinced it was in vain to strive any longer,
for I should never inherit the kingdom of heaven.
But a liar he was, and ever will be, and my soul is at enmity with him.
May the Lord, in whom I trust, preserve me and my house forever.

I was twenty-one years of age when I was in this condition.
But it pleased my heavenly Father,
(who had regard for me) to make a way of escape from this snare; for in a little time,
it was my lot to be at a meeting with that faithful servant of the Lord,
William Dewsbury.
A true messenger of the Lord this man was to many,
and on this day his testimony was mostly to the distressed and afflicted,
tossed with tempest and not comforted, in which state many found themselves at that time,
1655.
After the meeting had ended, I dreaded to go to him,
for I thought he was one of great discerning and
would be sensible of the hardness of my heart;
and if he should judge me, I would not be able to bear it.
Yet I found I could not go away in peace until I had spoken with him.
Seeing me approach him so heavily, he held up his hand, and with a raised voice,
said unto me, "`Dear lamb, judge all thoughts and believe;
for blessed are they that believe and see not.`"
And then, with a raised voice again said, "`They were blessed that saw and believed,
but more blessed are they that believe and see not.`"
Oh, he was one who had good tidings for me,
and great power was with his testimony at that time;
for the hardness was then taken away,
and my heart was opened by the ancient power which opened the heart of Lydia (Acts
16:14). Everlasting praises be given unto Him that sits upon the throne forever,
who has preserved me out of the snares and subtle contrivances of the adversary.

My soul cannot help but bless and praise the Lord my God,
who has preserved me out of the evil of the world.
My dear children, you have been brought up in the way of truth,
and it has been made known to you.
Therefore, trust in His name,
and believe that He will keep you unto the end--which
He will assuredly do if you depart not from Him.
My prayers are both night and day for you.
And you may well remember the many dangers you have been preserved out of,
which could well have been a hazard to your lives.
But the Lord, of His infinite goodness, has hitherto kept you all that you may serve Him.

Therefore my children, forget not your duty to the Lord,
nor the counsel that Jesus Christ gave to His disciples,
which was to watch and pray that you may be preserved out of all dangers,
both inward and outward.
These you may easily fall into, if you do not keep close to the Guide of your youth.
But if you keep to Him, He will never depart from you.
And if you "`keep in remembrance your Creator in the days of your
youth,`" then He will surely keep you in the hour of temptation,
and will take care of you.
If you "`seek first the kingdom of God, and His righteousness,
all other things shall be added unto you.`"
He has spoken who cannot lie; therefore put your trust in Him forever.
Then my heavenly Father will do for you even as He has done for me,
in the days of my tender years.
For He took me by the hand and led me by a way I knew not.
He made darkness light before me,
and has preserved me to this very day in covenant with Himself.
"`Everlasting praises and honor be given to His holy name forever,`" says my soul.

You may remember many of the straits and difficulties
the Lord has enabled me to go through,
though but weak and greatly afflicted with sickness, and very near the grave many times.
The Lord renewed my strength again and again to bear a
faithful testimony for Him and His blessed truth.
Various hardships has the Lord, my Redeemer, brought me through,
and when I look back and consider how my soul has escaped to this very day,
I am filled with admiration.
But this saying of Christ Jesus often comes before me, "`Greater is He that is in you,
than he that is in the world.`"
And the Lord said to His disciples, "`Be of good cheer, I have overcome the world.`"
Indeed, these have been a comfort to me many times.

I often remember a saying of a faithful servant and minister of Jesus Christ,
whose name was Miles Halhead, when I was under a great exercise.
He steadfastly looked upon me and said, "`Dear child, if you continue in the truth,
you will make an honorable woman for the Lord,
and the Lord God will honor you with His blessed testimony.`"
And ten years after this, in 1665, he came again to my habitation and said to me,
"`My love and life is with you, for the sake of the blessed work that is going on in you.
May the Lord God keep you faithful,
for He will require harder things of you than you are aware.
And may He give you strength to perform His will,
and keep you faithful to His blessed testimony.
My prayers shall be for you as often as I remember you.`"
Soon after this, the Lord opened my mouth in a testimony,
and a great exercise fell upon us,
for we were exposed to much suffering through loss of goods,
beatings and hurling to and fro, dragging out of our meeting-house,
and many other abuses.
Because of our persecutors, we went to our meetings in great hazard of our lives.
The informers were so wicked and inhuman, and filled with such envy and madness,
that they swore "`It was no more sin to kill us,
than it was to kill a louse;`" and "`that they would bathe their swords in our blood.`"
And all these things were the least of our sorrows, for in this time of great suffering,
a selfish, separating spirit began to break forth among Friends as well.
But truly I could say, "`My heart is given up to serve the Lord, come what may.`"
And blessed be the Lord our God, who lives forever,
we were in no way affrighted at these things, nor concerned at them;
for we knew that He in whom we believed was able to
deliver His chosen ones who put their trust in Him.
My dear children, some of these things you know, for your eyes have seen them.
And though you were but young and tender, yet the Lord kept you from the fear of men.

In this time, there fell upon me another great exercise of spirit,
which seemed so strange and wonderful that I could not
believe the Lord would require such a service of me,
for I was so weak and contemptible, so unfit and unlikely, my understanding but shallow,
and my capacity but mean and very low in my own eyes.
Looking so much at my insufficiency made me strive hard against it;
crying often-times within myself, "`Surely this must be something to ensnare me,
for the Lord could not require such things of me,
seeing there are so many wise and good men who are more
honorable and fit for service than I. Oh Lord,
remove this far from me, and require anything else of me, that I can better perform!`"

Thus did I reason and strive against Him,
till my sorrow was so great that I knew not whether the Lord would ever accept me again.
Then I cried unto the Lord again and again, "`Lord, if You have found me worthy,
make my way plain before me, and I will follow You;
for You know that I would not willingly offend You.`"
But knowing myself to be of a weak capacity,
I did not think the Lord would make choice of such a contemptible instrument as I,
nor desire me to leave my habitation and tender children (who were young),
to go to King Charles, a hundred miles off,
and deliver such a plain testimony as the Lord did require.

This made me go about bowed down for many months under the exercise of it;
and oftentimes I strove against it.
But I could get no rest,
except in giving up to obey the Lord in all things that He required of me;
and though it seemed hard and strange to me, yet the Lord made hard things easy,
according to His promise.
When I was going from my children,
and knew not but that my life might be required for my testimony,
the will of the Lord appeared so plain; yet as I looked upon my children,
my heart yearned towards them.
Then these words ran through me, "`If you can believe,
you will see all things accomplished, and you will return in peace,
and your reward will be with you.`"
Forever blessed be the name and power of the Lord, for He sustained me in my journey,
gave me strength to do His will,
and afforded me His living presence to accompany me--
which is the greatest comfort that can be enjoyed.

[.offset]
This was my testimony to King Charles II, in the eleventh month of the year 1670.

[quote]
____
This is unto you, O king:
Hear what the Lord has committed unto my charge concerning you.
As you have been the cause of making many desolate, so will the Lord lay you desolate;
and as many as have been the cause of persecuting and
shedding the blood of My dear children,
in the day when I call all to an account, I will plead with them, says the Lord.
Therefore hear and fear the Lord God of heaven and earth,
for of His righteous judgments all shall be made partakers;
from the king that sits upon the throne, to the beggar upon the dunghill.
____

This testimony I delivered into his hands, with these words, "`Hear, oh king,
and fear the Lord God of heaven and earth.`"
I can truly say, that the dread of the most high God was upon me, which made me tremble,
and great agony was over my spirit, insomuch that paleness came over the king`'s face,
and with a mournful voice he said, "`I thank you, good woman.`"
My soul honors and magnifies the name and power of the Lord my God,
for keeping me faithful to His testimony, and giving me strength to do His will,
for truly He made good His promise, that "`If I could believe, I should return in peace,
and my reward should be with me.`"
So the Lord blessed my going forth.
His presence was with me in my journey, He preserved my family well,
and my coming home was with joy and peace in my bosom.
Everlasting praises, glory, and honor be given to Him that sits on the throne,
and to the Lamb forevermore.

May you remember the goodness of the Lord to His children,
who faithfully follow and obey Him with their whole hearts,
though they may be attended with many weaknesses.
I gave way to the reasoner many times,
till my sorrow has been so great that I have not known which way to turn.
Indeed, this has dimmed my sight, and hurt my life, and plunged my soul into trouble.
But it pleased the Lord to appear in a needful hour,
and to turn back the enemy of my soul`'s peace.
And He has shown me that He will choose the weak,
and those who are nothing in their own eyes, and can do nothing--no,
not so much as utter a word but what the Lord gives them.
Thus the Scriptures of truth are fulfilled in this our day, as it was in times past,
that no flesh should glory in His presence.

A little time after,
the officers came and demanded money for the king because of our meeting together.
My husband answered them, "`If I owed the king money, I would surely pay him;
but seeing I owe him no money, I will pay him none.`"
They asked leave to seize his goods; to which he said, "`If you will take my goods,
I cannot hinder you, but I will not give you leave to take them;
neither will I be accessory to your taking them.`"
The officers saw our innocence, for we were in our shop at our lawful calling,
with our hands to our labor, and our children with us.
Then the constable (whose name was John) leaned his head down upon his hand,
and with a heavy heart, said,
"`It is against my conscience to take their goods from them.`"
Then I said, "`John, have a care of wronging your conscience;
for what could the Lord do more for you than to place His good Spirit in your heart,
to teach you what you should do, and what you should leave undone.`"
He said, "`I know not what to do in this matter.
If paying the money once would do, I would do it myself, but it will never end.
It will continue to be thus while you keep going to meetings;
for the rulers have made such laws, that never the like was seen in any age.`"
I said, "`John, when you have wronged your conscience,
and brought a burden upon your spirit, it is not the rulers who can remove it from you.
And if you should go to the rulers, and say,
'`I have done that which was against my conscience to do,`' then
they may say to you what the rulers said to Judas,
'`What is that to us? You see to it.`'`"

The officers who were with him came and pulled down our goods,
but the power of the Lord smote them,
insomuch that paleness was in their faces and their lips quivered,
and their hands did so shake that they could not hold our things long.
Then they charged a poor man to take them, but he refused, until they forced him,
and laid our goods upon his arms and shoulders.
But he, looking much like a dead man, replied,
"`You force me to do that which you cannot do yourselves;
neither can I.`" He trembled very much, though we had said nothing after they came in,
but rather rejoiced that the Lord had found us worthy
to suffer for His blessed truth and testimony.

A little time after,
there was a meeting to appraise the goods taken from us and other Friends.
Many were met together in a house--seven men called justices, the officers and sheriffs,
a bailiff, and many more of their confederates, a great room full of them.
I was at work in our shop,
and seeing the constable carrying away some of the goods to be appraised,
it immediately came into my heart to go after them.
I did not know one word that I should say to them,
which made me consider a little why I should go;
but it more and more rested upon me to go.

When I came within the door,
I sat down like one that was a fool for half or three quarters of an hour,
not having one word given me to say.
But when I came in, they became greatly disquieted in their minds,
and hurried in their business.
They said,
"`We can do nothing while she is with us,`" and the justices
called one to another many times to cause me to be taken away,
saying, "`We shall not do any business this day,
but spend our time in vain if this woman sit here.`"
They often tempted me to speak what I had to say, and then be gone;
but they could not prevail with me.
Then they called to the man of the house to take me away,
solemnly protesting never to come to his house again if he would not take me away.
But the man had no power to touch me, and being full of trouble, said, "`Sir,
I cannot lay hands on her, for she is my honest neighbor.`"
Then he turned towards me and said, "`Please neighbor Stirredge,
if you have anything to say, speak, that you may be gone.`"
One of the justices in great rage and fury,
solemnly protested he would never sit with them any more if they did not take me away,
and he marveled at their folly for letting me alone.
He then opened the back door and went out, as though he would be gone.
But in a little time he came in again, saying, "`What!
Is she still here? I wonder at your folly!`"

At last, the power of the Lord fell upon me, and filled my heart with a warning to them.
I said to them, "`It is in vain to be found striving against the Lord and His people.
Your work will not prosper;
for you will find the great God of heaven and earth to be too strong for you.
I warn you to repent, and to amend your lives before it is too late;
for the Lord will smite you unaware and in an hour not expected by you.
Therefore, remember that the Lord has granted you a day of warning,
before destruction comes upon you.`"
This, and much more ran through me at that time,
and the Lord was pleased in a very short time to fulfill this testimony upon them.
For in a few weeks, as they were making merry at a feast,
two of them died on a sudden after dinner, and the rest very hardly escaped.
This was about the year 1674.

I write this not to rejoice at the fall of our enemies,
but for you to consider the goodness and mercies and
dealings of the Lord with His people in all ages,
and to keep in remembrance His lovingkindness and forbearance to the very wicked,
who are provoking Him to pour down His vengeance upon their heads.
Yet so great is His mercy that He always warns the wicked,
and gives them time to repent and amend their lives,
that He may be clear in the day of account, which will surely come upon all.

Therefore, my dear children, remember your latter end and the day of account,
and keep a bridle to your tongues; for he that knows not a bridle to his tongue,
his religion is vain.
And keep always to the daily cross, which is the power of God to salvation.
If you will be heirs of the kingdom of heaven, and of the crown immortal,
you must take up the daily cross, for "`No Cross, No Crown.`"^
footnote:[No Cross, No Crown is the title of William Penn`'s famous book,
written during his imprisonment in the Tower of London in 1669.]
The cross will keep your minds in subjection to the living God; and being in subjection,
and standing in awe that you sin not,
it will keep you near to the Lord in a living acquaintance with Him.
Then He will take delight to bless you more and more, to instruct you,
and to counsel you in His way, which is pure and holy,
and will not admit any unholiness or uncleanness.

Beware of the world and its people.
Be not in too much familiarity with them, nor let in their spirit to mix with yours;
for this has been the hurt of many who have made
a good beginning and been traveling in the way,
yet have erred for lack of watchfulness and keeping to
the guide of their youth--the light of Christ Jesus.
This is the way to salvation, and whoever comes in any other way is a thief and a robber.
The way you know; you have been trained up in it.
And now the concern of my spirit is that you may keep in it,
and be concerned for your children, as your father and I have been concerned for you.
Train them up in the way of truth,
and keep them out of the beggarly rudiments of this world,
that they may grow up in plainness,
and keep to the plain language (which has become a very indifferent
thing today among many professors of truth.) Truly I was not clear in
the sight of God--my way was hedged up with thorns,
and I could go no further--until I had yielded obedience to Him in the little things.
Then I walked alone in private,
as I frequently used to do whenever things came as a weight upon me.
Oh, that desolate place where I used to retire alone,
how many times has my soul met with my Beloved there,
who has sweetly comforted me when my soul was sick from love,
and full of doubts for fear He had forsaken me.
But blessed be His name who lives forever, He appeared in a needful time,
when my soul was distressed for Him; it was then I came truly to prize Him.
Yes, this is the way of the Lord`'s dealing with His people,
that He may teach them to be humble, and train them up as children,
that they may learn obedience in all things to do His will.
And this is His end in chastening--to make His children fit for His service.

I little thought that the Lord would have spared me so many
years to bear a faithful testimony to His blessed truth,
and the powerful appearance and breaking forth of His glorious
light and life unto many thousands who sat in darkness.
Oh these were in a miserable state, many times past hope of ever seeing a good day,
with horror, dread, and anguish in their hearts!
But it was these who received and prized the blessed
offer of God`'s everlasting love and glorious appearance,
though it was in the way of His judgments.
And I can truly say that my heart and soul delighted in judgment,
even though one woe was poured out after another.
Yet blessed be the day in which the everlasting truth was first sounded in my ears,
which was in the nineteenth year of my age;
that it may never be forgotten by me is my soul`'s desire.
But more blessed be the name of the Lord our God, and the right arm of His power,
which has been made bare from day to day, and from year to year,
for the carrying on of His work, and the preservation of His children.

[.asterism]
'''

__Elizabeth Stirredge was never a minister in the Society of Friends,
but she was known by all to be one who "`stood in the counsel of the LORD,
perceiving and hearing His word`" (Jer. 23:18). She was faithful with little,
and the Lord entrusted with much,
giving her grace and wisdom to strengthen many fellow travelers on the narrow path.
Throughout her life she kept herself low and little before her almighty Master,
bowing before His least appearance, and clinging closely to His cross.
Being thus small in her own eyes,
the Lord was free to exalt and use her for His own glory and purpose,
which He frequently did, often in very remarkable ways (see the remainder of her journal,
Friend`'s Library vol. 2).__

__Like many others who held fast to the Truth in that day,
Elizabeth Stirredge knew her share of persecutions and imprisonments,
and at times "`joyfully accepted the plundering of her goods.`"
Incredibly, she welcomed such trials as signs of the Lord`'s love to her,
often saying she had no greater joy than to be counted worthy to suffer for His name.__
