== Life of Elizabeth Stirredge

Seeing the Lord hath been pleased to count me worthy to travel in Zion`'s way,
and I have found it so straight and narrow, and so many that have been called,
and some who have entered into it have gone into bypaths and crooked ways again;
and I have found the blessed effect of keeping in the right way,
therefore I have a great concern upon my spirit for my children,
who are coming up after me, that they may not be forgetful of keeping in the right way,
whensoever the Lord shall be pleased to take me from them.

It is in my heart, as my heavenly Father will be pleased to assist me,
to leave a short testimony behind me, for my children, of some passages of my life,
and of the goodness of the Lord to me all my life long, unto this very day,
which is worthy forever to be had in remembrance;
and in reverence to the worthy name and power of the Lord is it spoken,
and he shall have the praise of his own work forever.

1634+++.+++ I was born at Thornbury, in Gloucestershire, of honest parents;
my father`'s name was William Tayler; and my parents were people fearing God,
and very zealous in their day.
My father being one of those called Puritans,
prophesied of Friends many years before they came.
He said, "`there is a day coming, wherein truth will gloriously break forth,
more gloriously than ever since the apostles`' days, but I shall not live to see it.`"
He died in the faith of it seven years before Friends came;
whose honest and chaste life is often in my remembrance,
and his fervent and zealous prayers amongst his family, are not forgotten by me.

My parents brought me up after a very strict manner,
so that I was much a stranger to the world and its ways.
In my tender years I was of a sad heart, and much concerned, with inward fear,
what would become of me when I should die;
and when my lot was to be near any who would talk rudely, or swear,
or be overcome with strong drink, I dreaded to pass by them.
When I heard it thunder, oh, the dread and terror that would fall upon me!
And I would get to the most private place that I could, to mourn in secret,
thinking the Lord would render vengeance upon the heads of the wicked.
When I saw the flashes of lightning, oh, thought I,
whither shall I go to hide myself from the wrath of the dreadful and terrible God!
Thus was I possessed with my soul`'s concern; and before I was ten years of age,
was so filled with fears and doubts,
that I could take no delight in anything of this world.

When I grew up to riper years, I went to hear those accounted the best men,
who lived up to what was made known to them.
I delighted to hear them, and be in company with those who talked of good things,
and discoursed of Scripture, of God and Christ, and of heaven`'s glory.
Oh! how delightsome was it to me; but still I was not satisfied,
because I found I was not a living witness of the states
and conditions that the people of God were in,
in former days; and how to attain to them I did not know.
Then did I mourn, and say in my heart, oh,
that I had been born in the days when the Lord spake to Moses,
and to the children of Israel,
and with a high and wonderful power brought forth his people out of Egypt,
through the Red Sea, that I might have known how to walk in the right way,
and to do what the Lord required of me,
and been in acquaintance and familiarity with my Maker;
that I might have known when I pleased or displeased the Lord, whom my soul loved,
but knew not how to become acquainted with him.
What would I not have parted with for the enjoyment of the Lord,
and assurance of salvation?
Surely if it were possible for me to have enjoyed all the world,
I could freely have parted with it,
for peace and satisfaction to my poor distressed soul, that mourned as without hope.
Many a time, and many hours have I spent alone, reading and mourning, when no eye saw me,
nor ear heard me, neither could I find comfort in reading,
because it was a book sealed unto me.
Then did I mourn and say,
oh! that I had been born in the days when our blessed
Saviour Jesus Christ was upon the earth!
How would I have followed him, and sat at his feet, as Mary did;
how freely could I have left my father`'s house, and all my relations,
for true peace and assurance of life eternal for my immortal soul.

Under this exercise I grew very sad,
insomuch that my mother apprehended I was going into a consumption,
and greatly feared my death; and would say to me, "`Canst thou take delight in nothing?
I would have thee walk forth into the fields with the young people, for recreation,
and delight thyself in something.`"
And to please her, I have sometimes, when we were out of our employment,
gone forth with sober young people, but I found no comfort in that.
Then I fell into a custom of reading the Scriptures, alone in private,
reading and crying,
because I knew not that heavenly power and spirit to have dominion in me,
that was in them who gave forth the Scriptures;
and nothing else but the substance would give me true satisfaction:
therefore the Scripture was but a book sealed unto me.

Then I fell down upon my knees, to pray unto the Lord, with my heart full of sorrow,
and the tears running down my face, and could not utter one word;
which seemed very strange to me, and set me to thinking that there was none like me.
But it was the enemy`'s work to persuade me there was none like me;
and that because I could not pray in words, as others could, and was under afflictions,
therefore the Lord had no regard to me.
But the enemy is a liar, for the Lord was near me in every exercise, and broke my heart,
and melted my spirit, or else it would not have been so with me.
Oh! my soul can now behold his goodness, for he was near me,
although I was not aware of it; and thought none were so miserable as I,
the enemy endeavouring to cast mo down, and to make me despair.
Truly it was the great mercy of the Lord that preserved me from it,
for my affliction was great, and my distresses very many,
the enemy following me with temptations,
and I wanted right information where my strength was to be found,
which was to have stood still,
and waited upon the living God for strength to overcome him.

Instead of doing so, the enemy disturbed me, and followed me with his subtle allurements;
sometimes to draw my mind into the vanities of this world,
and to delight in decking myself with fine clothes,
that I might appear comely in the eyes of the world.
For, said the enemy, as for this sadness and trouble that thou art under,
it will redound to no advantage, nor comfort;
thou wilt not be in any esteem amongst thy neighbours, therefore,
take thy pleasure and be at rest.
A liar he is, and ever was from the beginning; and my dear children, believe him not,
if it be your lots to be under temptations, or exercise of any kind;
or what way soever the Lord may be pleased to lead you in,
for the trial of your faith and patience.
The enemy will betray as many as he can, therefore look unto the Lord,
and keep him in your remembrance, and pray unto him in your minds,
although you cannot utter one word; know assuredly,
that he is near to help his afflicted children at all times.
Oh! that I had known this in the days of my ignorance, in my young and tender years,
when the Lord was at work in my heart, and I knew it not.
For want of an understanding, the enemy betrayed me and led me aside in those things,
by hearkening to him and the young people who were my neighbours,
in persuading me that it would be of great benefit to me, for I was young,
and knew not what I might come to.
I was left of my tender father, with hardly any friend;
and in my distress and afflictions, willing to have a little rest and comfort,
I lent an ear to the enemy of my soul, and let my mind go forth after fine clothes.
When it was drawn out, it went without limit;
and when I decked myself as finely and as choice as I could,
it would hardly give me content; for when I had one new thing, and saw another,
or a third, I was as desirous of it as for the former, and so ever unsatisfied.
The lying enemy had promised me rest and peace, but could not give it;
a liar he is and ever was, my soul is at enmity with him;
the Lord preserve me out of his snares, and my house also forever.

But though he had thus drawn out my mind, the Lord did not leave me;
for many times I had a concern what would become of me;
and if at any time I was drawn into mirth or laughter,
I would feel something smite my heart, and bring great heaviness over my spirit.
I knew not what it was, and little thought it was the Lord,
who was ever good and gracious, kind, merciful and slow to anger,
and not willing people should run into destruction.

I little thought he looked so narrowly to my ways;
but since the Lord hath been pleased to open my eyes,
I can look back and admire his goodness; and blessed be his worthy name,
and the right arm of his strength, who hath early been my guide,
and kept me in great degree from running into the evil of the world,
which greatly attends young people.
He took me by the hand, and led me when I knew it not, in my tender years;
and if I had not hearkened unto the enemy, my condition had been well.
As soon as he had drawn my mind into pride, and to take delight in fine clothes,
they became my burden.
For in a little time after, in 1654, the Lord in the riches of his love,
was pleased to fit and send forth his faithful servants, and painful labourers,
whose industry he greatly prospered--two men of worthy memory,
dear John Audland and John Camm; and when I heard the report of them,
it struck a dread over my heart.
Hearing of their plainness, I began to think,
"`How shall I demean myself to go to hear them.`"
In a little time after, there was a meeting appointed by them, where it was my lot to be.
Dear John Audland was preaching as soon as I heard his voice, it pierced me;
when I came into the meeting and heard his testimony, and beheld his solid countenance,
oh! how my heart was troubled within me,
insomuch that I knew not what would become of me.

After meeting was over, I separated myself from my company,
and travelled alone two miles, that no ear should hear me, making my moan unto the Lord;
and out of the bitterness of my spirit, said "`Lord, what shall I do to be saved?
I would do anything for assurance of everlasting life:
and if the Lord will be pleased to accept me upon any terms,
I matter not what becomes of this body.
If I could find a cave that I might get into,
where I might mourn out the remainder of my days in sorrow,
and see man no more,`" I thought I could have been contented.
But it pleased the Lord to open the eyes of my understanding,
and to lead me by a way that I knew not, and to begin the first day`'s work in my heart,
which was, "`the spirit of the Lord moving upon the waters,
and dividing the light from the darkness.`"
When the separation was made, I could see my way in the light,
which was the "`light unto David`'s feet,
and a lamp to his paths;`" and it will order every ones`' goings aright,
if they take heed unto it.

It would be too tedious to go through every particular state;
but my earnest cries were to the Lord, "`to lead me by the right way,
and to create in me a new heart, and renew a right spirit within me.
Let me be unto thee, O Lord, what I am, and not unto man:
I do not take care for this outward body; do but redeem my soul from death,
out of this horrible pit, wherein I am held as in chains of darkness,
and shall perish forever, if thou dost not, out of thy infinite mercy,
have compassion on me, and bow thy ear unto my cries, for I can do nothing else.`"
I can truly say, my heart was filled with sorrow, my sighing came before I eat,
and tears were as my sorrowful meat; when I lay down, it was in sorrow,
and watered my pillow with my tears, before I could lake my rest: and when I awaked,
it was with the dread of the Lord over my heart.

Oh! my soul can do no less than magnify the living God, who is worthy of praise,
honour and renown, thanksgiving and obedience forevermore.
And why so?
Because he hath condescended to the lowest estate of his handmaid,
and bowed his ear to my prayers, and had a regard unto my cries,
and hath answered my request, and given me my heart`'s desire,
which was to be led in the right way.
Zion`'s poor travellers know very well this is a beginning, or a step in the way,
for I can truly say, "`that I never coveted heaven`'s glory,
more than I desired to walk in the way that leads thereunto.`"
And I truly believed, that the Lord would redeem a people out of the world,
its ways and customs, language, marriage and burying, and all the world`'s hypocrisy.
I looked for this change, before I saw any appearance of it; but all my fear was,
I should not live to see it; the enemy always following me with his temptations,
to work me into unbelief, and to cast me down into desperation.
My soul cannot but give the Lord God the glory, the honour and the renown,
for he is worthy of it forever, and evermore.

And now my dear children, this is for you to remember, and keep by you,
that ye may always know the way to heaven`'s glory, to enjoy true peace and satisfaction;
it is a straight and narrow way; and whoever thinks it is not, they are mistaken.
Keep to the daily cross all the days of your lives, and to truth`'s language:
and more especially keep your heart with all diligence,
for out of it are the issues of life.
Then will you be brought nearer unto the Lord, and grow into acquaintance with him;
which was what my soul mourned for in the days of my tender years, which I cannot forget,
and I hope never shall; for I find the good effects of it from day to day.
It bows my spirit, and humbles my heart,
and keeps me in a living remembrance of what the Lord has done for me;
though he hath been pleased to give me the waters of a bitter cup to drink,
and to feed me with the bread of affliction,
and suffer temptation upon temptation to come near me.
The enemy, the subtle serpent, the old dragon,
which was more subtle than all the beasts of the field, followed me with his lies,
to persuade me that the Lord had no regard to me; that if he had,
he would not take delight to afflict me;
"`for there is none like thee,`" said the wicked one, "`thou mayest look abroad,
and see where thou canst find one whose sorrows are like unto thine.`"

Then would I wander alone in some remote place, where no eye could see me,
nor ear hear me, to make my moan unto the Lord,
who hath sweetly comforted me and refreshed my spirit many a time,
and hath kept my head above the waters.
Blessed be the worthy name of the Lord my God, and the right arm of his strength,
that hath wrought wonderfully for my deliverance; and cursed is the old dragon,
who ever envied man`'s prosperity.
He endeavoured to destroy the blessed work of the Lord, as much as in him lay,
after the Lord had done much for me, and in a good measure redeemed my soul from death,
and by a high hand and stretched out arm, had brought me out of Egypt`'s darkness,
and through the Red Sea,
where my soul had true cause to sing praises unto the most high God,
who lives forevermore.
Oh! let me never forget this great and wonderful deliverance,
but keep in that which will bow my heart from day to day,
and humble my spirit before the Lord,
who "`hath been pleased to do more for me than my tongue is able to declare.
And although I can say mine eyes have seen afflictions, and no affliction seems joyous,
but grievous for the present,
yet afterwards it brings the peaceable fruits of righteousness.

And now, my dear children,
my aim is to make you a little acquainted with the work of the Lord in my heart,
and also with the subtle devices, and contrivances of the enemy of your immortal souls.
His way is to set his baits according to people`'s nature,
for therein he is most likely to prevail.
And because I was of a sad heart, and very subject to be cast down,
therefore did he with all his might endeavour to cast me into despair and unbelief;
persuading me I should never hold out to the end.
Then would I pray to the Lord, to preserve me to the end,
for my affliction was very great, both inward and outward,
and many things he cast before me, that seemed too hard for me to go through.
When my mind was sorrowful, the enemy got ground upon me,
and filled me with imaginations, until my heart grew hard before I was aware of it,
and I had lost that sweet enjoyment and heavenly fellowship with which I was comforted.
I had great cause to magnify the worthy name of the Lord,
who was pleased to comfort my afflicted soul;
but when the enemy had gotten a little ground,
he set his baits so agreeably to my nature,
that when I had any remembrance of the condition I was in before,
and now for a little time had lost, I had great cause to mourn to the Lord,
who was able to deliver me, as he had done many times; blessed be his holy name,
and the right arm of his strength, which lives forever.
And though he was able to do it, yet the enemy prevailed upon me a little further,
when I was making my complaint to the Lord, saying in my heart,
there is no sorrow like mine.
And why none like thine?
because I had lost my beloved, and my loss was great:
he that had redeemed my soul from death and had done well for me; oh!
I could do no less but mourn for him.
This mourning was very suitable to my condition,
had I been aware of that subtle serpent who was persuading me that I was discontented,
a murmurer and complainer, and made the Lord weary with my crying,
and that I should be shut out of his kingdom;
for it was the murmurers and complainers who perished in the wilderness.

I was soon caught by his subtlety,
for he persuaded me it was in vain to strive any longer;
I should never inherit the kingdom of heaven.
But a liar he was, and ever will be, my soul is at enmity with him;
the Lord in whom I trust, preserve me and my house forever.
It pleased my heavenly Father, who had a regard to me, to make way for me to escape;
for in a little time after, it was my lot to be at a meeting,
where a faithful servant of the Lord was, by name William Dewsbury,
whose testimony was mostly to the distressed and afflicted,
tossed with tempest and not comforted; which state many were in, in that day, 1655.
A true messenger he was to many.
I was twenty-one years of age when I was in this condition, and after meeting was ended,
I dreaded to go to him, for I thought he was one of great discerning,
and would be sensible of the hardness of my heart; and if he should judge me,
I should not be able to bear it: but yet I could not go away in peace,
until I had been with him.
Seeing me coming so heavily, he held up his hand, and with a raised voice said unto me,
"`Dear lamb, judge all thoughts and believe,
for blessed are they that believe and see not.`"
And with a raised voice again said, "`They were blessed that saw and believed,
but more blessed are they that believed and saw not.`"

He was one who had good tidings for me,
and great power was with his testimony at that time; for the hardness was taken away,
and my heart was opened by that ancient power that opened the heart of Lydia;
everlasting praises be given unto him that sits upon the throne forever,
who hath preserved me out of the snares and subtle contrivances of the adversary.

My dear children, you have been brought up in the way of truth.
It is made known to you; and my soul cannot but bless and praise the Lord my God,
who hath preserved me out of the evil of the world; therefore trust in his name,
and believe that he will keep you unto the end; which he will assuredly do,
if you depart not from him; which I hope you will not whilst you live;
and my prayers are both night and day for you.

I can truly say, that when any of our family have gone out of our habitation,
though upon outward occasions,
my prayers have ascended to the Lord for their preservation;
and unto this day the Lord hath heard, blessed be his name.
For you may well remember the many dangers you have been preserved out of,
that have been likely to hazard your lives; but the Lord, of his infinite goodness,
hath hitherto kept you all, that you may serve him.
Therefore, dear children, forget not your duty to the Lord,
and the counsel that Jesus Christ gave to his disciples, which was, to watch and pray,
that you may be preserved out of all dangers, both inward and outward,
which you may be liable to fall into, if you do not keep to the guide of your youth.
But if you keep to Him, he will never depart from you;
and "`keep in remembrance your Creator in the days of your
youth;`" then will he keep you in the hour of temptation,
and will take care for you.
If you "`seek first the kingdom of God, and his righteousness,
all other things shall be added unto you;`" he hath spoken it that cannot lie,
therefore put your trust in him forever.
Then will my heavenly Father do for you, as he hath done for me,
in the days of my tender years.
He took me by the hand, and led me by a way I knew not, he made darkness light before me,
and hath preserved me unto this very day in covenant with himself;
everlasting praises and honour be given to his holy name forever, saith my soul.

You may remember, since you have had an understanding,
the straits and difficulties the Lord hath enabled me to go through,
though but weak and greatly afflicted with sickness, and very near the grave many times.
The Lord renewed my strength again,
to bear a faithful testimony for him and his blessed truth.
Various straits and hardships hath the Lord, my Redeemer, brought me through,
which when I look back and consider, I am filled with admiration,
in remembering how my soul hath escaped to this very day.
But this saying of Christ Jesus often comes before me, "`Greater is he that is in you,
than he that is in the world;`" and he said to his disciples, "`Be of good cheer,
I have overcome the world;`" this hath been a comfort to me many times.
I often remember a saying of a faithful servant and minister of Jesus Christ,
whose name was Miles Halhead, when I was under great exercise:
He steadfastly looking upon me, said, "`Dear child, if thou continue in the truth,
thou wilt make an honourable woman for the Lord;
for the Lord God will honour thee with his blessed testimony.`"
And ten years after, in 1665, he came to my habitation, and said to me,
"`My love and life is with thee,
and that for the blessed work`'s sake that is going on in thee;
the Lord God keep thee faithful, for he will require harder things of thee,
than thou art aware of; the Lord give thee strength to perform them,
and keep thee faithful to his blessed testimony; my prayers shall be for thee,
as often as I remember thee.`"
Soon after, a great exercise fell upon us; we were exposed to much suffering,
and the Lord had opened my mouth in a testimony but a little before.
I have been concerned, for fear my friends should suffer for me; but not for myself;
for I could truly say, "`My heart was given up to serve the Lord, come what would come.`"
But the least of our sorrow was loss of goods, beating and hurling to and fro,
and dragging out of our meetinghouse, and many other abuses,
which the Lord made us able to go through, and sanctified to us;
and my soul blesseth the Lord, that he accounted us worthy to suffer for his name sake.

For in the time of suffering,
a selfish separating spirit began to break forth amongst us;
which added to our affliction more than all our persecutors could do;
though we went in great hazard of our lives to our meetings,
the informers were so wicked and inhuman, and filled with envy and madness,
that they swore "`It was no more sin to kill us,
than it was to kill a louse;`" and "`that they would bathe their swords in our blood.`"
But blessed be the Lord our God, who liveth forever,
we were in no wise affrighted at these things, nor concerned at them;
for we knew that He in whom we believed,
was able to deliver his chosen ones who put their trust in Him.

My dear children, some of these things you know, your eyes have seen them;
and though but young and tender, yet the Lord kept you from the fear of men.
In this time, there fell upon me another greater exercise of spirit,
which seemed so strange and wonderful,
that I could not believe the Lord would require such a service of me,
who was so weak and contemptible, so unfit and unlikely, my understanding but shallow,
and my capacity but mean and very low in my own eyes.
Looking so much at my insufficiency, made me strive hard against it;
crying often-times within myself, "`Surely this is something to ensnare me,
for the Lord does not require such things of me,
seeing there are so many wise and good men,
who are more honourable and fit for such service than I. Oh Lord, remove it far from me,
and require anything else of me, that I can better perform.`"

Thus did I reason and strive against it, till my sorrow was so great,
that I knew not whether ever the Lord would accept of me again.
Then I cried unto the Lord again and again, "`Lord, if thou hast found me worthy,
make my way plain before me, and I will follow thee;
for thou knowest that I would not willingly offend thee.`"
But knowing myself to be of a weak capacity,
I did not think the Lord would make choice of such a contemptible instrument as I,
to leave my habitation and tender children, who were young, to go to King Charles,
an hundred miles off, and with such a plain testimony as the Lord did require of me;
which made me go bowed down many months under the exercise of it;
and oftentimes strove against it.
I could get no rest,
but in giving up to obey the Lord in all things that he required of me;
and though it seemed hard and strange to me, yet the Lord made hard things easy,
according to his promise to me, when I was going from my children,
and knew not but my life might be required for my testimony, it was so plain;
and when I looked upon my children, my heart yearned towards them.
These words ran through me, "`If thou canst believe,
thou shalt see all things accomplished, and thou shalt return in peace,
and thy reward shall be with thee.`"
Forever blessed be the name and power of the Lord, he sustained me in my journey,
gave me strength to do his will, and afforded me his living presence to accompany me,
which is the greatest comfort that can be enjoyed.
This was my testimony to King Charles II., in the eleventh month, of the year 1670.

[.embedded-content-document.testimony]
--

This is unto thee, O king:
Hear what the Lord hath committed unto my charge concerning thee.
As thou hast been the cause of making many desolate, so will the Lord lay thee desolate;
and as many as have been the cause of persecuting
and shedding the blood of my dear children,
in the day when I call all to an account, I will plead with them, saith the Lord.
Therefore hear and fear the Lord God of heaven and earth,
for of his righteous judgments all shall be made partakers;
from the king that sitteth upon the throne, to the beggar upon the dunghill.

--

This testimony I delivered into his hands, with these words, "`Hear, oh king,
and fear the Lord God of heaven and earth.`"
I can truly say, that the dread of the most high God was upon me, which made me tremble,
and great agony was over my spirit; insomuch that paleness came in his face,
and with a mournful voice he said, "`I thank you good woman.`"
My soul honoureth and magnifieth the name and power of the Lord my God,
for keeping me faithful to his testimony, and giving me strength to do his will,
and he made good his promise, that "`If I could believe, I should return in peace,
and my reward should be with me.`"
So the Lord blessed my going forth, his presence was with me in my journey;
preserved my family well, and my coming home was with joy and peace in my bosom:
everlasting praises, glory and honour be given unto Him that sits on the throne,
and to the Lamb forevermore.

May you remember the goodness of the Lord to his children,
who faithfully follow and obey him with their whole hearts,
though they may be attended with many weaknesses, and are at times crying to the Lord,
"`Oh my weakness, I am not able to go through this great work,
neither indeed am I worthy.
There are many honourable wise men whom thou hast prepared for thy service,
that are fitter than I am; and there seem so many mountains and difficulties in my view,
that it appeareth too wonderful for me to go through.`"
I gave way to the reasoner many times, till my sorrow hath been so great,
that I have not known which way to turn, and it dimmed my sight, and hurt my life,
and plunged my soul into trouble.
But it pleased the Lord to appear in a needful hour,
and turn back the enemy of my soul`'s peace, and show me, that he would choose the weak,
and them who were nothing in their own eyes, and could do nothing; no,
not so much as utter a word but what the Lord giveth them; I mean,
in testimony for the living God,
that the Scriptures of truth may be fulfilled in this our day, as it was in times past,
that no flesh should glory in his presence.
Then did I freely give up to obey the requirings of the Lord with peace and comfort,
and received the blessed reward in my bosom, as I have already said.
Our exercise continued by our persecutors;
but blessed be the name and power of the Lord for his infinite mercies,
according to the day, so was our strength.

A little time after,
the officers came and demanded money for the king for our meeting together.
My husband answered them, "`If I owed the king any, I would surely pay him;
but seeing I owe him no money, I will pay him none.`"
They asked leave to distrain his goods; to which he said, "`If you will take my goods,
I cannot hinder you, but I will not give you leave to take them;
neither will I be accessary to your taking them.`"
The officers seeing our innocency, for we were in our shop at our lawful calling,
with our hands to our labour, and our children with us,
the constable leaned his head down upon his hand, with a heavy heart, and said,
"`It is against my conscience to take their goods from them.`"
Then I said, "`John, have a care of wronging thy conscience;
for what could the Lord do more for thee than to place his good spirit in thy heart,
to teach thee what thou shouldest do, and what thou shouldest leave undone.`"
He said, "`I know not what to do in this matter; if paying the money once would do,
I would do it, but it will not end so; it will be thus, whilst you keep going to meeting;
for the rulers have made such laws, that never was the like in any age.`"
I said, "`John, when thou hast wronged thy conscience,
and brought a burden upon thy spirit, it is not the rulers who can remove it from thee.
If thou shouldest go to the rulers, and say,
I have done that which was against my conscience to do,
they may say as the rulers did to Judas, What is that to us, see thou to that.`"

The officers who were with him, came and pulled down our goods;
and the power of the Lord smote them,
insomuch that paleness was in their faces and their lips quivered,
and their hands did so shake, that they could not hold it long.
Then they would force a poor man to take them, but he refused, until they forced him,
and laid them upon his arms and shoulders; but he, looking much like a dead man, replied,
"`You force me to do that which you cannot do yourselves,
neither can I.`" He trembled very much, though we had nothing farther to say to them,
after they came in,
but could rejoice that the Lord had found us worthy
to suffer for his blessed truth and testimony.

A little time after,
they had a meeting to appraise the goods taken from us and other Friends;
where there met together seven men called justices, and the officers and sheriffs,
bailiff, and many more of their confederates, a great room full of them.
I was at work in our shop;
and seeing the constable carrying some of the goods to be appraised,
it immediately came into my heart to go after them,
not knowing one word that I should have to say;
which made me a little consider for what I should go;
but it more and more rested with me to go.

When I came within the door, I sat down like one that was a fool,
and had not one word to say, as near as I can count the time,
for half or three quarters of an hour.
But when I came in, they were greatly disquieted in their minds,
and hurried in their business.
They said,
"`they could do nothing whilst I was with them;`" the justices
calling one to another to cause me to be taken away many times;
saying, "`We shall not do any business this day, but spend our time in vain,
if this woman sit here.`"
They often tempted me to speak what I had to say, and be gone;
but could not prevail with me.
Then they called to the man of the house to take me away,
solemnly protesting never to come to his house again, if he would not take me away.
But the man had not power to touch me, but full of trouble, said, "`Sir,
I cannot lay hands on her, for she is my honest neighbour:`" and turning him towards me,
said, "`Pray neighbour Stirredge, if you have anything to say, speak,
that you may be gone.`"
One of the justices in great rage and fury,
solemnly protested he would never sit with them any more, if they did not take me away;
oftentimes wondering at their folly, for letting me alone.
Then he opened the back door, and went out, as though he would be gone,
but in a little time came in again, saying, "`What! is she here yet?
I wonder at your folly!`"
Then the power of the Lord fell upon me, and filled my heart with a warning to them;
telling them, "`That it was in vain to be found striving against the Lord and his people;
their work would not prosper;
for the great God of heaven and earth would be too strong for them.
Therefore I warned them to repent, and amend their lives before it be too late;
for the Lord will smite you at unawares, and in an hour not expected by you;
therefore remember that the Lord hath afforded you a day of warning,
before destruction comes upon you.`"
This, and much more ran through me at that time;
and the Lord was pleased in a very short time to fulfill that testimony on them.
For in a few weeks, as they were making merry at a feast, two of them died on a sudden,
after dinner, and the rest very hardly escaped.
This was about the year 1674.

I write not this to rejoice at the fall of our enemies,
but for you to consider the goodness and mercies,
and dealing of the Lord with his people in all ages;
and to keep in remembrance his lovingkindness and forbearance to the very wicked,
who are provoking him to pour down his vengeance upon their heads.
Yet so great is his mercy, that he always warns the wicked,
and gives them time to repent, and space to amend their lives,
that the Lord may be clear in the day of account; which day will surely come upon all.

Therefore, my dear children, remember your latter end, and the day of account,
and keep a bridle to your tongues; for he that knows not a bridle to his tongue,
his religion is vain.
And keep to the daily cross, which is the power of God to salvation.
If you will be heirs of the kingdom of heaven, and of the crown immortal,
you must take up the daily cross, for "`No cross, no crown.`"
The cross will keep your minds in subjection to the living God; and being in subjection,
and standing in awe that you sin not, will keep you near to the Lord,
in a living acquaintance with him; then he will take delight to bless you more and more,
to instruct you, and to counsel you in his way, which is pure and holy,
and will not admit of any unholiness nor uncleanness.

Beware of the world and the people thereof; be not in too much familiarity with them,
nor let in their spirit to mix with yours;
which has been the hurt of many who have made a good
beginning and been going on their way,
yet have erred for want of watchfulness, and keeping to the guide of their youth,
the light of Christ Jesus, who is the way to salvation;
and whoever comes in any other way, is a thief and a robber.
The way you know; you have been trained up in it; and the concern of my spirit is,
that you may keep in it, and be concerned for your children,
as your father and I have been for you.
Train them up in the way of truth,
and keep them out of the beggarly rudiments of this world,
that they may grow up in plainness; and keep to the plain language, both you and they;
which is become a very indifferent thing amongst many of the professors of truth.
But in the beginning we went through great exercise for that very word,
thee and thou to one person.
For my part, I had a concern upon my spirit, because I shifted many times from that word.
I would have said any word, rather than thee or thou,
that would have answered the matter I was concerned in, but still I was condemned,
guilt following me.
I was not clear in the sight of God; my way was hedged up with thorns;
I could go no further, until I had yielded obedience unto the little things.
Then I walked alone, as I frequently used to do, when things came as a weight upon me,
where I might be private from all except my soul`'s concern.
Oh! that desolate place where I used to retire alone,
how many times hath my soul met with my beloved there, who hath sweetly comforted me,
when my soul hath been sick of love; and full of doubts, for fear He had forsaken me.
But blessed be his name who liveth forever, he still appeared in a needful time,
when my soul was distressed for him, and then was the time I truly prized him.
This is the way of the Lord`'s dealing with his people,
that he may teach them to be humble, and train them up as children,
that they may learn obedience in all things to do his will.
And this is his end in chastening, to make them fit for his service.

I little thought that the Lord would have spared me so many years,
to bear a faithful testimony to his blessed truth,
and powerful appearance in the breaking forth of his glorious
light and life unto many thousands who sat in darkness,
whose state was miserable and many times past hope of ever seeing a good day,
and at their wits-end; horror, dread and anguish was in their hearts.
Oh! these were they that would receive and prize the blessed
offers of God`'s everlasting love and appearance,
though it was in the way of his judgments.
I can truly say, that my heart and soul delighted in judgment;
though one woe was poured out after another;
yet blessed be the day in which the everlasting truth was first sounded in my ears,
which was in the nineteenth year of my age; let it never be forgotten by me,
is my soul`'s desire.
But more blessed be the name of the Lord our God, and the right arm of his power,
that hath been made bare from day to day, and from year to year,
for the carrying on of his work, and the preservation of his children.

The greatest exercise that ever I met with,
was concerning the separating spirit that first began
to appear in John Story and John Wilkinson,
about the year 1670.
I find a concern upon my spirit to leave a short
relation of my exercises in the service for the Lord,
his blessed truth and testimony, that he,
in the riches of his love had made my heart and soul a partaker of:
praises be given to his holy name forever.

In the year 1670, which was a time of great suffering amongst Friends,
and from that time forward, as it is well known,
we went to our meetings at the peril of our lives, and our goods were taken for a prey.
In this time of great exercise did this dividing spirit begin to appear,
and in a very crafty manner ensnared the hearts of the simple.
There were many whom the Lord had reached unto in
the breaking forth of his wonderful power,
and whom he had enriched both inwardly and outwardly,
but who had forgotten the days of their distress, where the Lord first found them out,
and had caused the offence of the cross to cease, and had gone into ease and liberty.
Oh! how did such fall in with them, to the grief of the souls of the faithful.

Our sorrow for the loss of our brethren, was greater than for all our persecutions,
or loss of goods, or all other abuses of what kind soever; indeed,
great was our sorrow on every hand, and my soul was mostly concerned for the Lord,
and his blessed truth and testimony.
How did my heart pant after the Lord, and my soul travailed night and day before him,
for strength to stand a faithful witness for the living God,
with whom I had made covenant,
where the Lord first met with me when I was bewailing myself, saying in my heart, "`Oh,
that I could find out a cave in the earth, wherein I might mourn out my days in sorrow,
and see man no more; or that the Lord would be pleased to accept me upon any terms;
or if my life would be accepted as a ransom for my soul,
I would be very willing to part with it.`"
The cry many a time ran through my heart, "`Oh Lord, what shall I do to be saved?`"

The appearance of the Lord in that state was very precious to me,
I very gladly entered into covenant with him, to serve him forever,
if he would redeem my soul from death,
and from under the power of him that was too strong for me.
And seeing the Lord in his infinite mercy was so good and gracious to me,
as to give me my heart`'s desire, how could I forget it?
No, rather let my right hand forget her cunning,
and my tongue cleave to the roof of my mouth,
before I should forget to pay the vows made to the Lord, in my distress.`"

And now to come to the matter, concerning this libertine spirit.--In the aforesaid year,
1670, when they began their work, the priest`'s son of our town was one of the informers,
and his curate another.
The priest`'s son bought a new sword, and swore he would bathe it in our blood; and said,
"`it was no more sin to kill a Quaker, than it was to kill a louse.`"
Thus they began their dreadful work, and it is too tedious to run through the particulars.
They first nailed up our meetinghouse door, and set a guard before it;
and it being on a day that the petty sessions was kept in the town of Kainsham,
four miles from Bristol, several justices being there,
they sent the bailiff and other officers, attended with a rabble,
who came in great rage with clubs and other weapons, but the Lord was gracious to us,
and gave us strength according to the day, and opened my mouth in a testimony,
for the encouragement of Friends, and in praise to God,
for counting us worthy to suffer for his name and truth`'s sake.
Afterwards, another woman spoke encouraging Friends;
and the power of the Lord was so livingly felt amongst us, that our enemies fell,
and could hardly speak to ask us our names.
At length we were fined twenty pounds a piece, and when meeting ended,
we came away rejoicing.
Indeed there was great cause for it;
for the power of God was over all to cur great comfort.

But for all this, the clouds gathered blackness, the storm raised higher and higher,
and dismal days appeared; and many set their wits at work,
and consulted together how to meet in private, out of our enemies`' sight.
It was but a little time that our meeting held together,
for one who had been a great preacher, was soon weary with standing in the street,
at our meetinghouse door; and was greatly offended with us,
for not leaving our meetinghouse, and meeting with him in his dwelling-house.
There was a little remnant that could not conform to the will of man,
but feared the Lord, and dreaded to deny him before men.

Then R. W. who was John Story`'s associate,
whilst the said John Story abode in our parts, sent a messenger to tell us,
"`that if we would come and meet with him, and some others in private,
we might sit together in quietness and stillness, and wait upon the Lord,
and enjoy the benefit of our meeting; which would be better than standing in the street,
to be hurried and thronged together, and hardly any time of stillness to wait upon God.`"
A very plausible bait the enemy cast in their view, and too many were taken in the snare.
But when I heard this message delivered from the wise preacher afore-named,
oh! the concern that fell upon me,
in consideration of those who had been preachers amongst us many years,
and should have been a strength to the weak, and encouragers of the people,
and feet to the lame, and eyes to the blind; that such men should have no more courage,
nor zeal, nor love to the Lord and his blessed truth.
It became my great grief, and I sorrowed night and day; Lord, strengthen thy weak ones,
and make the little ones as strong as David;
give us courage and boldness to stand as faithful witnesses for thy blessed truth.
And blessed forever be the Lord our God, he answered my request,
and according to the day was our strength renewed;
blessed be the hand that never failed us, nor any who put their trust in him.
So they parted from us,
and left us as it were in the open field to encounter with our enemies;
who the more triumphed, and made a byword of them and us, and cried out,
"`here are the fools, the wise men are gone.
Aye, said they,
they have more wit than to meet so near the justice`'s
house to aggravate him and ruin themselves;
they are wise men to save themselves, and what they have; but these are the fools,
they will ruin themselves do what we can:
a poor company of ignorant fools that know not their right hand from their left;
do you think to stand against all the powers of the earth?
A company of silly fools!`"

Thus they pleased themselves with such discourses.
To lose ground, was a grievous exercise to us,
in hearing any of our brethren thus spoken of,
who should have been as valiants in Israel,
and have gone before the little ones like valiant champions,
to bear the brunt of the battle,
that our enemies might have seen their courage and valour for the Lord of hosts;
that the Lord, through his instruments, might have been glorified,
and his blessed name and truth honoured and exalted over all;
who alone is worthy of all honour and praise forevermore.

But if any should say, "`was this a discouragement to you little ones?`"
I answer No, our fear and zeal towards God was increased; and I can say,
to the praise and honour of his everlasting name,
my cries and supplications ascended night and day unto Him,
for strength to stand in my lot and testimony,
and that I might be made able to hold out to the end.--And forever blessed be the Lord,
he strengthened my weakness, and made the weak as strong as David,
and afforded his living presence amongst us, to our great comfort.
But still my exercise increased, which drove me to a narrow search,
and a deep consideration, what should be the cause of my great exercise,
crying to the Lord, "`Lord, what wilt thou have me to do?
Wilt thou be pleased to make known thy will concerning me?
Is there anything lodges in my heart that offends thee?
Oh, purge it out, I beseech thee; search my heart, and try my reins,
for I love to be searched and tried.
Lord, wilt thou be better pleased for us to go and meet with our Friends who are gone from us?
Is there service there that we know not of; or am I too forward,
or over-zealous for thy truth?`"
To this inquiry, the answer suited my inquiring heart:
"`Keep your meeting-time and place; be valiant for my truth upon earth,
and I will crown you with honour.`"
Oh! blessed be his eternal name; no greater honour does my soul desire,
than to be preserved in his fear.

At another time in great exercise, it often sounded in my heart,
"`I will gather from far, from the east, west, north and south,
and they shall come and sit down in the kingdom, with Abraham, Isaac and Jacob,
and the children of the kingdom shall be cast out.`"
Then a concern fell upon me, and my cry to the Lord was,
"`Save the children of the kingdom; oh! gather from far,
and bring near them that are afar off; but save the children of the kingdom.`"
This thing was my daily and hourly exercise; many times saying within myself, "`O Lord,
save the children of the kingdom, or take me to thyself,
whilst thy mercy is continued unto me; let me not live to be cast out of thy kingdom.`"

Thus the Lord gently led me towards the service and
testimony that he was pleased to lay upon me to bear;
which was the greatest trial that I ever met with.
My exercise increased, my inward pains grew stronger and stronger,
my heart was troubled within me, my eyes were as a fountain of tears, and I cried out,
"`Woe is me, that ever I was born.
Oh! what is the matter that all my bowels seem to be displaced.`"
Then the word ran through my heart, "`My indignation is kindled,
and my anger is waxen hot against this people, and my controversy shall be with them;
the time is coming, that they will bring more dishonour to my name and truth,
than is brought by open profaneness,
and thou shalt be an instrument to proclaim it in their ears.`"
Which made me to tremble before the Lord, crying,
"`Oh Lord! why wilt thou require such hard things of me?
Lord, look upon my afflictions, and lay no more upon me than.
I am able to bear.
They will not hear me, who am a contemptible instrument.
And seeing they despise the service of women so much,
make use of them that are more worthy.`"
I oftentimes cried to the Lord to remove it from me, still crying out of my unworthiness,
"`Oh! how unfit am I for such service!`"
The answer I received was, "`They shall be made worthy,
that dwell low in my fear.`"--So we continued under great suffering,
a poor little remnant, as one may term it, in the open field,
to encounter with our enemies.
But forever magnified be the name and power of our God,
his presence was our life and strength, and according to the day, was strength given.
Wherefore we had great cause to say, "`Good is the Lord,
his mercies endure forever,`" and to praise his name,
that he made us worthy to suffer for his truth`'s sake;
keeping us faithful to stand for our God, and confess him before men.
For I can say to his praise, I was so encouraged in all times of persecution,
wherein I might bear my testimony for the Lord, who had redeemed my soul from death,
and raised me out of the pit of misery, that I rejoiced to do the will of the Lord,
for it was more to me than all that ever my eyes beheld,
and to stand a faithful witness for him.

I was constrained in the fear of the Lord, to warn them of the dreadful day of the Lord,
and to call them to repentance for their unfaithfulness;
and thus we went on in our continual exercise, and in the strength of the Lord,
and by the assistance of his holy power, were borne up in it.

But now to come to what is most before me,
that all may understand how the enemy works in a mystery,
and under a fair pretence to betray the precious life,
and from the simplicity of the Gospel, which is foolishness to the wisdom of the world.

In this troublesome time, it came in my heart to visit Friends in Wiltshire,
where I had heard much of John Story`'s actions.
He had much reflected upon several women,
for bearing their testimony against that spirit of separation.
I met with two good women who had been upon the service of truth,
and had a good testimony, whom he grieved, bidding them go home about their business,
and wash their dishes, and not go about to preach; and said,
that Paul did absolutely forbid women to preach; and sent them home crying.
And furthermore, he counselled Friends to use Christian prudence,
and remember what is said in Scripture, "`If you are persecuted in one city,
flee to another.`"
So he would have them to alter the day and time of their usual meeting.
There was a little meeting in a dwelling-house, and he importuned them to remove it,
or alter the time; and the woman Friend of the house was soon gained,
not being so zealous for the truth as she should have been.
Her husband, being more faithful, would not be caught in that snare.
She fell at difference with him, and said,
"`Dost thou think God doth not reveal his secrets to such as John Story more than we?
Yes, surely; and if the Lord is pleased to save us, and what we have,
and make him an instrument, why shall not we receive his counsel.`"
A very subtle bait, to catch the poor ignorant people.
This was a great grief to the sincere-hearted;
it caused many to know days and nights of sorrow.
But still this testimony always lived in my heart,
that God`'s anger was kindled against that spirit,
whose followers have turned their backs on truth`'s testimony;
and were not only fallen into that snare themselves,
but endeavoured to ensnare many more.
The concern of it began to come over me, insomuch that I dreaded to go to a meeting,
for fear that testimony would be required of me; but the time was not yet come.

There came a faithful servant of the Lord to our meeting, whose name was Miles Halhead,
who was wonderfully endowed with the power of the Lord, and great discerning.
He came to see me, and said, "`My love runs to thee,
and that for the work`'s sake that is in thee; for God will require hard things of thee.
Thou little thinkest what is at work in thy heart;
the Lord God of my life keep thee faithful! my prayers shall be for thee,
as often as I have thee in remembrance; thou art as my own life, and sealed in my bosom,
I cannot forget thee, so dear child farewell;
the Lord my God hath sent me forth once more, and when I return home,
he will cut the thread of my life in two.`"
And so it was.
But, oh, the goodness of the Lord with that salutation overflowed my whole heart,
and melted me into tenderness, and my eyes as a fountain of tears, saying within myself,
"`What am I but a poor helpless creature,
and am not worthy of the least of these great favours and
mercies that the dear servant of the Lord is speaking of:
and surely if the Lord be with me, why is it thus with me?
I am under great exercises daily, and straits many.`"
Sometimes it seemed to me, as if the Lord had withdrawn himself from me,
which caused great sorrow of heart.

In a little time after, our lots were cast at Bristol,
where John Story was most of his time, and the height of persecution being a little over,
he could preach one hour after another, whilst one word would hang to another,
to the hindrance of several travailing souls, who have been pained at the heart,
for a little time to ease their spirits and discharge their duty,
that all might have been comforted together.
But in the room of that, a cloud of darkness hath come over, which made many to groan.
Oh, the agony I have been in, to come forth with the testimony which had lived with me,
that I had been so long confirmed in.
Many nights and days, and weeks and months have I gone on in sorrow and pain,
and have eaten no pleasant bread.
And many times have I lain down in sorrow, and watered my pillow with my tears,
crying out, "`O Lord, what will become of me, and what shall I do?`"
And the Lord said, "`A testimony I do require of thee.`"
Then I said, "`O Lord, if thou wilt open my heart to declare of thy goodness,
and what thou hast done for thy people, and to tell of thy noble acts,
and thy manifold mercies, how ready should I be to do it; but these are hard things,
who can bear them?`"

Thus I did reason with the-Lord, till my burden became too heavy for me to bear.
When I have gone forth in my lawful concerns, and have seen any of them,
(the separatists,) pain did take hold of me, distress and anguish of spirit,
insomuch that I sought private places to mourn in, saying, "`What shall I do?
send me to a nation of a strange language, whose face I never knew,
and make use of a better instrument for this great work; they will not hear me,
who am a contemptible instrument,
neither do I know whether any of them will receive my testimony.`"

Not one knew for what I went through such great exercises;
many Friends said that something lay weightily upon me;
insomuch that I could hardly go on my feet,
and they wondered that I did not give up to it, and said,
that I hurt myself and the meeting too.

I cannot but greatly admire the mercy and lovingkindness of the Lord,
and his long forbearance with me,
in that he did not cut me off in my disobedience to him,
when I knew what he required of me, as well as I knew my right hand from my left,
and would not obey him.
But still I reasoned and cried out, "`What shall I do!`"
I thought that if any one had borne a testimony in public before me,
I could the better have done it; but to be one of the first, such a contemptible one,
I could not do it.
But what mercy did not do, judgment did.
The Lord was pleased to lay his hand heavy upon me,
and with his correcting rod chastised me;
and I felt more of the displeasure of the Lord for my backwardness to his requirings,
than ever I did for my former transgressions.
I may say, as true as ever Jonah was plunged into the deep,
and his head wrapped about with weeds, so was my soul plunged into a gulf of misery;
insomuch that all hope of ever finding favour with God again, was hid from me,
and I left to lament in sorrow, as one without hope.

How did my heart lament, and my soul languish night and day.
I said, "`Oh, that the Lord would be pleased to show mercy once more,
to raise up my life again,
and redeem my soul out of this horrible pit wherein I am held as with chains.
Bring me to my former state again, and require what thou pleasest,
and I will obey thy voice,
though I should be hated of all men upon the face of the earth.`"

And before I could take any rest, I made a deep engagement to the Lord,
to do whatever he required of me, if he would give me strength, and be with me.
So when first-day morning came, I had a great concern upon me;
and when I sat down to wait upon the Lord, the power of the Lord seized on me,
which made me tremble; insomuch that my bones were shaken, and my teeth chattered,
and I was in great agony.
I stood up with a dreadful testimony,
and proclaimed God`'s controversy with the exalted
and high amongst the professors of truth,
and such as had departed from the cross of our Lord Jesus Christ,
with whom God`'s anger was waxen hot.
I warned them to repent while they had a day, and more to that effect;
but as short as I could.
Then a Friend stood up with a great concern upon him, saying,
"`A living testimony is the God of heaven and earth
raising up amongst the poor and contemptible ones,
that shall stand over your heads forevermore.`"
So he went on in great authority, and the power of the Lord was manifested among us.
O glory be to his everlasting name forevermore, saith my soul,
for his blessed appearance to us that day, and for all his mercies,
who returned me an hundred fold into my bosom,
after all my unworthy consulting against the motions of
the spirit of so merciful and compassionate a Father,
who after he had corrected me received me into favour again.
Glory to him forevermore: for when I had cleared my conscience,
the peace and consolation I received from the Lord, were more to me than all the world,
or the friendship of it.

Some time after, John Story, and three of his party came to my house to rebuke me,
and were very high, and spoke great swelling words, thinking thereby to discourage me.
John Story asked me, what I had to lay to his charge, and what I had against him?
I told him, what I had against him, I never received from man,
nor by any information from any one; but what I have against thee,
is from the evidence of God in my own conscience.
"`The evidence of God in thy conscience,`" said he in a deriding manner,
"`that is not sufficient for thee!`"
I said it was sufficient for me; by what else should I try spirits,
but by the evidence of God in my own conscience?
So he said again, "`that was not sufficient for me!`"
My husband said, "`John, to what wilt thou bring us now?
Hast not thou, and all other Friends,
directed us to God`'s witness in our own conscience,
and now thou sayest it is not sufficient.`"
And he said again, "`It is not sufficient,
unless thou couldest bring witness that I had done some evil action,
and what could I accuse him of; or else what signifies it to have aught against him.`"

I could have laid enough to his charge of his manner of acting in time of persecution;
but being willing to be short with him, I said, I have this to say to thee,
that thy conduct in public meetings, differs much from the apostle, who said,
if anything be revealed to him that sitteth by, the first is to be silent.
Thou wilt take up the whole time of the meeting,
although there have been many that have been concerned before thy face, and that greatly;
so what thou doest, is not ignorantly, but willfully.
He answered me very angrily, and said, "`If I do do so, what canst thou make of that?`"
I said, "`Thou art out of the order of the Gospel; for it is said,
the church may exercise one by one; and thou dost not as thou wouldest be done by.`"
And further I told him, "`That this was not his place to abide here preaching,
and burdening the souls of the innocent; but thy place is to return home into the north,
and be reconciled to thy brethren, before thou go to offer thy gift.`"
Many great swelling words proceeded from him, and his three friends who were with him;
and they went away sorely displeased.

Their rage increased towards me and many faithful
Friends who had sat under their dead ministry;
but mostly against me, for discharging my duty,
in obedience to what the Lord required of me, and committed to my charge,
concerning that spirit which for some time endeavoured to lord it over God`'s heritage;
which made many sensible ones go bowed down many a time.
My soul is a living witness, with many more, of what I have here declared,
which is but little of their persecution towards me, in consideration of what follows,
for the Lord was pleased to continue my exercise in that city,
where John Story abode much of his time.
Several more of that spirit oftentimes frequented thither,
and the Lord was pleased to make me so sensible of them,
that in the night season I had many a sore travail of spirit,
when I knew not of them by information from any one.
Then did I cry unto the Lord in secret, "`What shall I do to go through such hard things?
Oh, that I may be excused, or that thou wilt be pleased to keep me in silence this day;
then should I be very willing to go to meeting to wait upon thee,
and to sit under the shadow of thy wing with great delight,
where thy fruit will be pleasant to my taste.`"
Then would come up before me,
the covenant that I made with the Lord in the days of my distress, when all the world,
and the friendship of it, would not yield one drop of comfort to my poor distressed soul.
I promised the Lord in that day, twenty years before,
that if he would redeem my soul from death, and give me assurance of life,
I would serve him all my days, if he would give me strength, and be with me;
for I mattered not what I went through for his name`'s sake.
It would often come up before me, that they who followed the Lord, and loved him most,
did whatsoever he commanded them.
I cannot but admire the long forbearance, and lovingkindness of the Lord,
that he had not cut me off in my gainsaying, and unfaithfulness;
for I never wanted the assistance of his holy Spirit, in giving up to his requirings,
blessed be the name of the Lord our God, and the right arm of his strength, forevermore;
who alone hath been our keeper and preserver to this very day;
glory be to his great name forevermore.

I shall give a little account of one meeting in Bristol,
which was one of the greatest exercises that ever I met with,
or ever went through since I had a remembrance.
When I was going to the meeting, I had a great exercise upon my spirit,
and knew not for what; but after some time of waiting upon the Lord, I saw my service,
for John Story was there, who came into Bristol the night before,
and several Friends had "`warned him not to come and offer his gift,
till he was reconciled to his brethren;`" for if he did,
they believed that the Lord would concern one or
another to bear testimony openly against him.
I knew not of it till afterward, for if I had,
I believe my service would not have been so hard and strange to me.
But whilst he was declaring, a great cloud came over the meeting,
and I was greatly exercised in my spirit; insomuch that the Lord constrained me to cry,
"`Woe to that spirit that dimmeth the glory of the Lord,
and woe to that pot whose scum remains in it,
for in it is the broth of abominable things, such as the Lord`'s soul loathes,
and the souls of his people also.`"
It ran through me again and again, and I was pressed in my spirit to declare it,
whilst he was speaking; but I was sensible what a disturbance it would be in the meeting.
I would fain have forborne till he had done, but I durst not; I was afraid to speak,
and afraid to keep silent.
If I had been silent,
I knew that I should have withstood the spirit of the Lord in my own conscience.
I strove against it by reasoning, and saying, "`Oh,
that the Lord would be pleased to excuse me this day,
and that I might not lose his favour, then I should have accounted myself happy.`"
All this reasoning, would not do the service that God had for me that day,
and when I found no way to pass it by, I stood up to clear my conscience,
and discharge my duty.
When I considered the weak condition I had been in, the Lord`'s strength sustained me,
for according to the day was strength given me;
glory to his everlasting name forevermore, saith my soul;
his blessed reward was returned into my bosom, and he renewed my strength,
and raised up my life in dominion over all the opposition I then met with.

Thus, reader, I have given this short account of the going forth and work of that spirit;
since which, I have seen a withering and decay come upon it,
near twenty years having passed over my head.

Oh, the unchristian-like treatment that has been brought forth by that spirit;
and how have some of them written and printed against truth,
and its good order--turned their backs in the day of battle,
and left their brethren in the hands of their enemies.
How grievous have their actions been since the year 1670.
Now let all consider whether the testimony that God
raised in my heart in that time of great distress,
was not true; for I can truly say,
I went under the exercise of their backsliding many times.
The Lord was pleased to exercise me, and cause me to go through a vale of tears,
and a land of drought, in order to humble me, that I might bow to his will,
and obey him in all things; "`For obedience is better than sacrifice,
and to hearken to the voice of the Lord, is better than the fat of rams.`"
There is no hearing his gracious voice, but by humbling ourselves under his mighty power;
then doth he make known his will, and blessed are they that hear his word, and obey it;
that know his will, and do it.
Blessed be his eternal name forever, saith my soul, for all his mercies, and favours,
and good gifts, and tokens of his gracious love that he hath bestowed upon me.
First, in keeping me out of the evil of the world in my tender years,
and preserving me from falling into many temptations, of which I had a great share;
and then for taking me by the hand, and leading me in his way,
and also opened my spiritual eye,
that I might see the way which led towards his glorious kingdom;
and for preserving me to this very day alive in his testimony;
and all his manifold mercies, which are in my view at this time.
In the remembrance of them my heart is truly bowed, and with hearty thanksgiving,
do return unto my heavenly Father all glory, and honour, and praise.
Everlasting renown be given unto my God, and our dear Lord and Saviour, Christ Jesus,
who is sitting upon his throne, judging in righteousness,
and swaying his sceptre in holiness; who is worthy forever to be feared,
honoured and obeyed, saith my soul, at this time, and forevermore.
Amen.

And now my dear children, it further lives in my heart,
to leave some of the testimonies that the Lord was pleased
to lay upon me in that time of great suffering in Bristol,
and near to it.

In the year 1680, I was greatly concerned to go to the mayor at Bristol,
with this testimony, on their session`'s day in the morning,
waiting at his door for his rising from his bed.

I met with him going through one of his rooms, before he was fully ready,
and said unto him,
"`The God of heaven and earth hath constrained me this night
and morning to come unto thee with this testimony;
therefore do not lay it by thee, as a thing not worth thy minding; but read it,
and well weigh and consider what is written therein;
for could I have been clear in the sight of God in not coming,
I had not been here this day.`"

[.offset]
Which testimony was as followeth:

[.embedded-content-document.testimony]
--

This is to the mayor, aldermen and officers of all sorts,
and all who have a hand in persecuting the righteous servants of the most high God,
called Quakers, who are dear unto the Lord, as the apple of his eye;
and the Lord hath said in the Scriptures of truth, "`Touch not mine anointed,
and do my prophets no harm.`"
Now consider you people of all sorts,
who have the Scriptures of truth so frequently amongst you:
O! do you make such ill use of them, as not to take notice what is written therein;
surely they were given forth for a better purpose; for the Lord our God,
who is full of compassion, and bowels of love towards the work of his own hands,
hath in the riches of his love provided a way wherein
people might escape his wrath and fierce vengeance.
The Lord hath placed a measure of his good spirit in your hearts,
that never consented to sin; which, if you give up to be guided by it,
will make you happy forever.
It would teach you to do unto all men, as you would all men should do unto you.
This is a good lesson for you to learn,
and would make you honourable in the sight of the nations,
and beautify you in the sight of the people.
Then there would be no rending, tearing or devouring, neither making havoc,
nor spoiling of our goods; no imprisoning of the servants of the most high God,
for the answer of a good conscience; no beating and throwing of the ancient and feeble,
because they cannot so hastily go out of the way, as your hasty wills would have them.
O! the God of heaven will plead for these things,
and a day of reckoning will the great and mighty Jehovah,
who is the God of the whole earth, call for.
And dreadful will he be in his pleading.
Oh! who will be able to stand before him, who is like a devouring fire;
and all the wicked, and all that forget God, shall be as stubble before him,
saith the Scriptures of truth.

O ye rulers, and people of all sorts, read the Scriptures,
and see what became of the persecutors in days past,
for they were written and left upon record for the
comfort of them that live the life of them,
and for warning of the wicked and ungodly.
Consider Dives in the days of his health, how he fared sumptuously every day,
and considered not poor Lazarus, that begged at his gate.
Oh! how hard-hearted was he!
But what became of him?
And what a dreadful place of torment is prepared for the wicked and for the ungodly,
wherein they are made to cry out, when it is too late,
for one drop of water to cool their tongues, and it shall not be granted them.
Therefore for the Lord`'s sake, and for your own souls`' sake, repent,
lest you perish to all eternity.
Wherefore the call of the Lord is once more sounded in thee, O city of Bristol,
and to the inhabitants thereof.
Oh, repent, repent before it be too late, and break off thy sins by true repentance,
and thy transgression by showing mercy: plead the cause of the innocent,
and let the oppressed go free, and be not worse than they of old, who cried, "`Help,
O men of Israel, etc.`"
There is a company of rude boys, and rabble of the basest sort, with the officers,
thronging in amongst us, pressing us together without mercy;
and the officers themselves taking us by the arms, and throwing us along,
until we can hardly recover ourselves; and pulling off the men`'s hats,
throwing them from them in great fury, and haling to prison many in a day.

Oh, be ashamed, ye rulers, and all who have a hand in this work;
and tremble before the great and terrible God that made you, and gave you breath,
and being: for he is able to dash you in pieces like a potter`'s vessel,
and to take away your breath, and to lay you as dead men before him.
Therefore consider, before it be too late;
before the days of your calamity come upon you,
and the arrows of the Almighty stick fast in you, and there will be none to help you,
nor to deliver out of his hands; for the Lord will assuredly visit this nation,
for the treachery and cursed oaths, pride and oppression of many therein,
whose sins have reached unto heaven.
It is the determination of the great God of heaven and earth,
to send his destroying angel amongst them, and thin them; great will be your sorrow,
pain and perplexity, terror, amazement and vexation of spirit.
Alas! for the day will be great--who shall be able to stand in it,
but the pure in heart and they that have made the Lord Jehovah their choice,
and love him above all things, as well in times of peace as in times of distress;
such shall dwell with the Lord forever.

And now, O you magistrates, consider what you are doing;
and you that are fathers of children, dishonour not your grey hairs so much,
as to be found encouraging such ungodly actions.
Oh! consider your places and wherefore the Lord created you; it was to serve him,
and not to serve sin, nor uncleanness.
And wherefore did the Lord our God, who is rich in mercy, ordain means,
or a way whereby men might escape the snare, but that he would have all to do well,
and live in his favour forever.
Be you all awakened this day, and aroused up, and sleep not in security,
for destruction is near if you do not speedily repent.
Consider the Sodomites of old, how they were toiling, and nothing would satisfy them,
but the servants of the most high God, whom he had sent to warn them;
and instead of being warned by them, they the more provoked the just and holy God,
who willeth not the death of sinners, but had rather they would return and live.
Therefore hath he sent his servants early and late to warn the people;
that by taking warning they might escape the wrath of the most high God,
that all are liable to fall into, who are adding sin unto sin.
And truly I know nothing more likely to draw down the vengeance of God,
than to use his children cruelly, and to make them groan under their oppression,
as Pharaoh did in his day, until their groans pierced the ears of the Lord, and he said,
"`I have heard the groanings of my people, and I am come down to deliver them.`"
And truly our God is as great in power, and as mighty to deliver at this day,
as he was in that day.
And if you do thus go on, as you have already done, your days will be shortened,
and you shall not prosper.

Therefore, consider it in time, I entreat you, as you tender the good of your own souls,
and your children`'s, and be not patterns of cruelty to succeeding generations:
leave not your names upon record for such ungodly actions, and unchristian-like dealings,
as persecuting your honest neighbours for keeping
their consciences void of offence towards God,
and all men; for it is because we fear the great God of heaven and earth who made us,
and gave us our breath and being, and durst not betray our Lord and Master,
as Judas did in his day; and mark what became of him.
I say, because we durst not deny the Lord, nor wrong our own souls,
therefore are we sufferers this day under your cruelty.
The just and righteous God of heaven and earth, will one day plead with all people,
and not one shall escape from his tribunal seat,
without a just recompense of reward for their deeds done in their life time.
He is no respecter of persons, he regardeth not the rich more than the poor,
he is just in all his judgments, and equal in his ways;
ever blessed and honoured be his worthy name and his honourable truth, saith my soul,
forever, and forevermore, Amen.

These things have been weighty upon my spirit,
and for the clearing of my conscience have I written them,
desiring your moderation may appear, and that noble spirit may arise in you,
which was in them of old, who, "`Tried all things, and held fast that which was good.`"
However it be, whether you will hear or forbear, I shall be clear in the sight of my God,
who said to his servant in the days of old, "`If thou warn the wicked,
and they turn not from their wickedness, yet thou hast delivered thy soul,
but his blood shall be upon his own head.`"

[.signed-section-signature]
Elizabeth Stirredge.

--

It further liveth with me to leave a relation of our suffering,
trials and imprisonment in the year 1683.
If it may fall to any of your lots to suffer for truth`'s testimony,
or for the answer of a good conscience in any case whatever,
I mean in things relating to the answer of a good conscience towards God,
which you may be assured to meet with during the time of your pilgrimage here;
I have this testimony to bear for the living God, and his everlasting mercies,
that amongst the many blessings and favours and deliverances
that we have been made partakers of from year to year,
for these seven and thirty years; of which, blessed be the name and power of our God,
he hath made me a living witness,
and an enjoyer of his blessed truth--amongst all the seasons of his love,
this was the greatest of mercies unto me.
For the God of heaven and earth was with us at our down-lying and up-rising;
and whilst we slept he kept us, and when we awaked he was present with us;
the right hand of his power upheld us; his good spirit sustained us,
and made hard things easy to us, and bitter things sweet.
When we awaited in the night season, spiritual groans ascended unto Him;
and in the morning light,
living thanksgiving and high praises were returned unto him that liveth forevermore;
who was the God and Father of all our mercies and blessings, and gave us strength,
courage and boldness to stand faithful to our testimony, to the praise of the Lord.
The terror of evil times did not affright us,
though our enemies determined our ruin and destruction,
and pleased themselves in afflicting us.

[.centered]
=== The Manner of Our Going to Prison, and by Whom we were Persecuted

Robert Cross, priest of the parish of Chew-magna, in the county of Somerset,
whither we removed some time before, and where we then dwelt,
was a great persecutor twenty years before; but having left it for some years,
began afresh with us, his rage being renewed against Friends,
for their faithfulness to the Lord, and his blessed truth.
He was greatly offended; but against me in particular, to that degree, that he said,
"`If he could but live to see me ruined, and my husband for my sake,
he cared not if he died next day.`"
That which enraged him against me was this; being with a neighbour who lay very weak,
on her deathbed, and several of the said priest`'s congregation being present,
I had to testify of a day of mortality to them,
which accordingly fell out to three or four in two weeks time, and was taken notice of;
the priest being told of it, was enraged,
and made use of several instruments for carrying on his cruel work.
He sent to the neighbouring justice, and threatened him,
that it should cost him an hundred pounds,
if he did not put the king`'s laws in execution against the Quakers,
as the justice told me himself, upon a time when they took me from a burial,
and had me before them; the manner of which comes up before me at this time.

At the burial of a daughter of one professing truth, I had a testimony to the people,
and many of the priest`'s company being there, it greatly offended him.
The next week after, the father of this young woman dying also,
the day of his burial happened on the very day that
several justices were met at their petty sessions,
near the burying-place of Friends.
They sent a warrant, with some officers, into our burying-yard,
to bring away preacher and hearers, if any one took upon them to preach,
there being a great concourse of people, many coming in with the officers,
to see what they would do to us; and a very great company with the corpse.
No sooner were we come into the yard, but the power of the Lord came upon me,
and made me tremble, so that I could hardly stand on my feet;
but taking hold on a Friend who was near me, I said, "`There is a day coming,
in which the God of heaven and earth will be too
strong for the stout-hearted amongst you:
therefore repent, and amend your lives, while you have a day and time;
for as the tree falls, so it lieth, and as death leaves, judgment finds,
for there is no repentance in the grave.
Therefore hasten, hasten to repentance, and amendment of life;
for the great God of heaven and earth will thin this nation,
for the people are too many who are sinning against the Lord.`"

This, and much more I said, for my heart was opened,
and my spirit greatly enlarged by the power of the Lord,
and drawn forth in love towards the people.
I saw the tears running down many faces, and many said,
they would never be again as they had been.
The officer standing by me with a warrant in his pocket, trembled exceedingly,
and could hardly open the warrant without rending it, crying,
"`Oh! that I had been twenty miles from my habitation,
that I had not had a hand in this work; pray do not take it ill of me,
for I am forced to it; you must go with me before the justices,
but I wish I had been farther off, then I had had no hand in troubling you;
pray do not be angry with me.`"
I said, "`Do not be troubled so much, I am not offended, I will go with thee.`"

When we came before the justices, one of them was greatly enraged against me; and said,
"`You are an old prophetess, I know you of old;`" he might well say so,
for he was one of those that I bore a testimony amongst ten years before.
He greatly threatened me, and said, "`I should go to prison,
and he would ruin my husband; but where is he?
He careth little for you, I will warrant you, else he would have come with you,
and not have suffered you to be sent to prison by yourself.
You are a troublesome woman, parson Cross complains of you; you scatter his flock,
and have done him more injury than all the Quakers ever did;
you made an oration at the daughter`'s grave the last week,
and now at the father`' s also: you shall certainly go to prison,
that shall be the least I will do to you.`"
Thus he went on in an outrageous manner, and I stood before him,
looking steadfastly upon him, and did not answer one word in this time; but he continued,
and said, "`You are a subtle woman;
your tongue is at liberty when you are with your conventicle; but you are dumb,
now you are come before us, I will send you to prison.`"
I said, "`I am not so much affrighted at a prison, as thou thinkest I am;
but if thou send me to prison, and shorten my days, because of my weakness,
thou wilt but bring innocent blood upon thy head,
and that will cry aloud for vengeance.`"

He said to me, "`Why do you break the king`'s laws then?
And why do you not go to church?
You are running headlong into Popery.`"
"`I deny the Pope,`" said I, "`and his actions.`"
"`Do you love the king?`"
said he, "`Yes,`" said I. "`Why do you not obey his law then?`"
said he.
"`I have broken no law this day;`" said I. "`I was at a burial,
and it is no breach of law to bury our dead.`"
"`Well,`" said he, "`you say you have broken no law,
will you keep the king`'s law for the time to come,
and leave off holding conventicles and preaching?`"
"`So far as the king`'s laws do not wrong my conscience,`" said I, "`I will keep them,
but I will not wrong my conscience for the king, nor any man else;
and I do not know whether ever the Lord may open my mouth again; but if he do,
and unloose my tongue to speak, I shall not keep silent.`"
"`So, you can talk now, when you please; but,`" said he to them that sat by him,
"`she will be dumb again by and by.
I will ask her one question that shall make her dumb again.
Well, you say you have not broken the king`'s laws, you were but at a burial,
but I will warrant you held a conventicle amongst the people at John Hall`'s house,
before you brought him forth; what say you to that?`"
I did not presently answer him, until he said again, "`Why don`'t you answer?
I knew she would be dumb.`"
Then I answered, "`I am no informer, Judas was an informer, when he betrayed his master.`"
Then he looked on those who were by him, and said,
"`I tell you these Quakers are the subtlest people that we have to do with,
there is no dealing with them; one while they will not speak at all,
and another while give such cross answers as this; I protest I will send her to prison.`"
He called the clerk to make my mittimus, and the officer was called for;
then he raged at him, and said, "`You silly fellow, you have let all the men go,
and have brought a troublesome woman here to trouble us;
you should have brought two or three rich men to have paid for all the conventicle.`"

"`Sir, I did not know them,`" said he.

"`No, I will make you swear you do not know them; give him the book;
make him kiss the book.`"

The poor man was so scared at it, that he cried, "`Pray Sir, don`'t you do it,
I cannot swear.`"

Then I looked on the justices, and said,
"`My soul is grieved to see how you oppress men`'s spirits,
in forcing them to wrong their consciences;
do you not think that the just and righteous God will visit for these things?
Yes verily, a day of reckoning will the great God of heaven and earth call for,
and terrible will it be to all the workers of iniquity.`"

Then the other justice who sat by, and had forborne meddling all this time,
being a moderate man, who was not forward in persecuting his neighbours;
seeing the other so furious, said, "`Let us come to the matter in hand:
this woman was at a burial, and there are many religions in the world,
and all have their way to bury their dead, and we cannot hinder them.
Officer, let us know the truth of the matter, was this a conventicle, or no?
If it was, there must be a place prepared for her to stand up over the people to preach;
was it so?`"

"`No, Sir,`" said the officer.

"`What then stood she on?`"

"`Nothing but the earth of the grave.`"

"`And what said she?`"

"`I never heard the like in all my life,`" said he; "`she said there was a day coming,
in which the God of heaven and earth would be too
strong for the stout-hearted amongst us;
and proclaimed a day of mortality amongst us,
and warned us to repent and amend our lives; surely it made my heart tremble.`"

"`How!
What a woman make your heart to tremble?`"

"`Yes Sir, and I had no power to touch her,
until she had said all she had in her heart to say.`"

"`How,`" said the angry justice, "`You silly fellow, you an officer,
and had a severe warrant in your pocket, to bring away preacher and hearers,
and you let her say all she had to say; you are not fit to be the king`'s officer;
send him away to prison.`"

Then the moderate justice went out of the room, and sent one to desire me to go out also;
I was not forward to go, for that honest confession of the poor man, did me more good,
as I thought, than my release at that time.
The justice returning in again, said,
"`Pray neighbour Stirredge go home about your business.`"
So I returned to my habitation again, and had the peace of the Lord in my bosom;
everlasting praises be given to the Lord our God.

This wicked priest, after the burial, went from house to house,
and threatened the people,
that it should cost them five pounds a piece for going to hear the Quakers.
Some being frightened at his threatening, asked him forgiveness:
others said they would go again.
But still he continued his rage, for nothing would content him but our ruin.
He had sent the officers to our meeting, who dealt roughly with us,
by pulling and throwing, and`" threatening; all which did not content him;
but as he was preaching in his pulpit, he fell down as dead,
whilst the words were in his mouth; as many of the hearers then present,
declared unto me that they thought he would never have drawn breath again.
But after a great ado, and all means used that they could, he recovered a little.
The people said,
we hope it will be a warning to him to leave off persecuting his neighbours.
But it was not, for he was heard to say,
"`That if he could but live to accomplish that work he had begun,
he did not care if he died presently.`"
Seeing his neighbours not forward in answering his will,
he sent to Bristol for John Hellier, with more of his confederates,
who was the great persecutor at Bristol, whom he thought did his work to the full.
They came with many officers, into our meeting at Chew-magna, five miles from Bristol,
where we were solemnly met together to wait upon the great God of heaven and earth;
rushed in amongst us, arrested us all in the king`'s name, and left a guard upon us,
then went to the priest`'s house to dinner, and stayed near two hours.
In which time, we had our meeting peaceably, wherein we enjoyed the presence of the Lord,
to our souls`' comfort, who never failed his children in a needful hour,
but always gave them strength suitable to the day;
everlasting honour be given to his holy name.

After they had fed to the full, and drank abundance,
they brought with them faggots of wood from the priest`'s,
with a hatchet and a great axe, and commanded the people to assist them.
So they mustered up their force as they came along;
and the people seeing what posture they were in, cried out, "`What are you going to do?`"
"`Blow up the house, and burn the Quakers,`" said they.
Then they threw down their wood at the meetinghouse door, and cried out,
"`Set fire on them, blow up the house.`"
The people cried out, "`it will burn our houses that are near,
and you will not be so wicked as to burn the people, will you?`"
Then they came in, in a violent manner, and laid hands on the children,
threatening to burn them; bringing some out, they said,
"`We will make them a warning to all others,
and make them repent that ever they were Quakers.`"

Then they laid hands on us, hauling and dragging us along, beating some with a cane,
and hewing off the legs of the forms, and taking other forms by the two ends,
threw the Friends backwards that sat thereon;
often calling to our neighbours to aid them.
Some of them replied, "`We cannot work on the sabbath day.`"
So they continued until they had wearied themselves;
then bringing us all out into the street amongst many people, I said unto them,
"`Where is your teacher?`"
"`What is that to you,`" some replied, "`you shall be sure to suffer,
if the rest do not.`"
"`But where is your teacher?`"
I said again, "`Let him come and see the fruit of his labour; this is his flock,
and this is your sabbath day`'s work, let him come and behold the fruits of his labour,
and see if he will not be ashamed of it.`"
Then they forced us in again, and John Helliar caused his man to make our mittimus,
and himself committed us to Ivelchester jail, where we were cruelly used,
as is after related.

John Helliar being the principal man in this work, our head-borough asked him,
what he should do with us?
He replied, "`Have them away to prison presently.`"
The day being far spent, and the journey long,
it being twenty-two miles to the county jail, he asked John Helliar how we should go?
For here are many women who cannot travel on foot.
He answered, "`I will press some carts to haul them along.`"
I said,
"`We are not ashamed to be carted for the testimony of our Lord and Master Jesus Christ.`"

So they returned to the priest, and told him they had done his work effectually,
for we were all committed to prison.
He put off his hat, and thanked them, and said, "`It would add years to his life;
now he should live in peace.`"
But take notice how short his days were.
The head-borough, on the morrow morning,
went and told him he must provide horses to carry the Quakers to prison.
He answered, "`The devil should have us first.`"
He asked what he should do to get us thither?
"`Drive them along like hogs,`" said the priest.
The officer was our neighbour, a moderate man,
and what he did was sorely against his will.
He came from the priest`'s house, to ours, and told us what he said.
So before we were carried to prison, the priest was walking in the steeple-house yard,
where he had a great deal of foolish discourse with some boys who were there at play,
too tedious to mention.
But the last words were,
"`He bid one of the boys take a halter and hang himself:`" and then he fell down dead.
His family being called, brought forth a chair and other things necessary,
and lifted him therein and used all means they could to restore him,
there being many people about him; some crying out, "`Don`'t you disturb the old man,
but let him go quietly;`" "`aye,`" said others,
"`let him depart in peace and don`'t you disturb him, that his neighbours, the Quakers,
may abide at home, and not go to prison.`"
Some of the neighbours came into our shop, and said, "`Now you may abide at home,
for Mr. Cross is fallen down dead in the church-yard.`"
And he was going mad before, said the mother of one of the boys,
for he bid my boy take a halter and hang himself.
Lord have mercy upon me!
What wicked counsel was that of a minister, said she;
we were in good hopes that his falling down in the
pulpit would have been a warning to him,
but it was not.
After an hour and an half`'s time, he had so much life,
as that he called them that were about him rogues.
So they carried him in his chair, to his bed, where he remained some days, and died;
but never sensible, as I was informed by several.
We were carried to prison before he died, where we had hard usage.

Our keeper, Giles Bale, and his wife, put us in the common jail, with three felons,
who were condemned to be hanged, and would not afford us straw to lie upon,
though we would have paid for it.
Living some distance from the prison, they locked us up,
and carried away the key with them,
to prevent the under-keeper from showing us any favour: and the head keeper`'s wife said,
"`There let them be, like a company of rogues together;--if I had a worse place,
I would put them in it.`"^
footnote:[This keeper and his wife died soon after, and their family came to ruin.]

It was a most dismal place, where we had neither stock nor stone to sit upon;
nor any resting place to lean against, but the black stone wall, covered over with soot,
and the damp cold ground to lie upon.
But before we lay down,
three of our Friends who were prisoners in the room adjoining to that we were in,
put through the grates to us four dust or chaff pillows, and two blankets,
and a little straw, whereon we lay down, like a flock of sheep in a pen,
in a very cold winter, the like of which I do not remember;
where most of us took our rest very sweetly.
But when I lay down, the consideration came into my heart,
"`Lord thou knowest for what we are exposed to this hardship;
it is because we cannot betray our testimony, nor wrong our conscience,
nor deal treacherously with our own souls.
And seeing it is so.
Lord, be thou our comfort in this needful time;
for it is thy presence makes hard things easy, and bitter things sweet;
and thou hast sweetened the waters of a bitter cup.
Oh! thou Physician of value, who can strengthen both soul and body,
be with us this night, and all the nights and days that we have to live in this world.`"
Then the Lord was pleased to open my heart unto him,
and to fill it with his mercy and comfortable presence,
insomuch that I could have sung aloud of the goodness of the Lord,
and of his mercies and blessings bestowed upon us.
But looking over my fellow prisoners, and seeing them so sound asleep,
I forbore to open my mouth.

In the morning there came many people to the prison door,
to see how many of us were dead with our hard fare; some of them were sure, as they said,
that I was dead, for I looked as if I would not live until the morning.
Finding us all alive and well, they confessed and said,
"`Surely we were the people of God, if there were any.`"
It being the first-day, we had a meeting in the prison, and many Friends came there,
where we had a very good meeting, and the presence of the Lord was with us,
and filled our hearts with joy and gladness,
insomuch that I was constrained to praise the name of the Lord, and magnify his power,
and to testify in the hearing of many people,
that we were so far from repenting our coming there,
that we had great cause to give glory,
honour and praises to the Lord God of heaven and earth,
because he had found us worthy to suffer for his name and truth;
for his presence was with us, and sanctified our afflictions,
and made the prison like a palace to us; and we would not change our state,
for all the glory of the world, if it were proffered unto us.

Great was the goodness and mercy of the Lord towards us from day to day;
that I have sometimes said, surely the Lord is honouring his people,
and weaning them from this world.
It seemed to me as if I had no habitation but the prison:
then was the time for the Lord to reveal his secrets unto his children,
whom he had tried and proved in such things.
It was faithfulness that rendered the servant acceptable in his master`'s sight,
and caused him to say, "`Well done thou good and faithful servant,
thou hast been faithful in a little, be thou ruler over much.`"
I cannot believe, that he who is not true in a little, will ever be made ruler over much:
therefore keep to truth in all things, and to the plain language,
and teach your children so to do.
In that time of great affliction and suffering, and parting of many, wife from husband,
and husband from wife, and both from tender children;
the Lord was pleased to reveal his secrets to his children.

Seeing the goodness of the Lord,
and being made sensible of his gathering arm from day to day,
a great concern came upon me for many careless ones,
who had deprived themselves of that blessed benefit
which our souls enjoyed with the Lord.
In consideration of their deplorable state,
my soul hath often been poured forth before the Lord, crying, "`O Lord,
that they may come and partake of thy great mercies, as we do from day to day.`"
Then it would come before me,
how greatly they had dishonoured the Lord and his blessed truth,
by their unfaithfulness and unbelief.
Yea, they could not trust the Lord, as if he had not power or strength to preserve them.
I cried, O Lord, many are weak and feeble,
and the cruelty of men hath been great and desperately wicked;
and thou hast suffered them to be very cruel, to the astonishment of many;
insomuch that many a poor soul hath been tossed as with a tempest;
and for want of keeping to that blessed guide and rock, Christ Jesus,
who alone is able to give them boldness and courage
to go through the work of this day of affliction,
many a poor one hath fallen,
not knowing they should be deprived of so great a reward as we enjoy;
blessed be thy holy name forever.
And Lord, thou knowest that my heart is pained within me,
my soul is in travail towards the poor and the distressed, the tossed with tempests,
and not comforted; the enemy of their souls is busy to cast them down,
and to fill their minds with trouble and unbelief,
always casting before them their unfaithfulness, and would fain keep them in bondage,
and from returning unto thee by true repentance,
that thou mayest heal their backslidings,
and teach them to be more faithful for time to come.
O Lord! what shall I do for them?
They are often in my remembrance; Lord, open my heart in prayer more and more,
and bow thy car to the supplication of thy servant, as thou hast done many times;
and accept of the prayer of thy servant, for them who cannot pray for themselves.
O Lord! if it may stand with thy blessed will, once more afford them a day of visitation,
and try them again.
Deal not with them according to their deserts; but, I pray thee,
have compassion on the work of thy hands, and remember poor mortals this day;
for surely many of them are greatly distressed and compassed about with many temptations,
and my heart is pained for them.

In this mournful state,
the Lord was pleased to speak comfortably to me in the secret of my heart,
in the spring of life, and said, "`The time of the deliverance of my people draweth near,
and nearer than many are aware of;
though I have suffered their enemies for a time to triumph over them,
yet too many have grown high and lofty,
and forgotten the days of their distress and calamity,
and what state they were in when I first found them out; as it were without hope:
then did I send forth my light and my truth,
which many received with thankfulness of heart, and with a ready mind,
and bowed thereunto, and yielded obedience for a time.
But after I had confounded their enemies, and appeared for their deliverance,
and enriched them greatly, they forgot the days of their distress and poverty,
and the many promises which they made to me in the
day when they were sorely beset with enemies,
within and without.
Since I have appeared for them, and confounded their foes,
and have done more for them than they looked for,
how have they forgotten to pay their vows unto me,
which many of them made in the days of their distress!
How far are they gone into old Israel`'s sins?
Nay, have not some so much lost their senses, as to put light for darkness,
and darkness for light?

"`But blessed are all they who continue truly humble, for my covenant is firm,
forever established, and never to be altered with my remnant who have been faithful,
that have parted with all that I have called for, for my name and truth`'s sake;
and who have had no helper in the earth but me, none to lean upon, or to confide in,
but the arm of my power; who could not turn to the right hand or to the left,
unless I went before them.
These are mine, and my secrets shall be with them,
they shall be found worthy to stand in the gap, and to intercede for the people;
notwithstanding their poverty and nothingness of themselves;
yet they shall be as instruments in my hand, to proclaim my dreadful day,
and the day of my vengeance amongst the people, that many may hear and fear,
and turn unto me by true repentance, that I may heal their backslidings,
and receive them freely.
And in order thereto, I will bring a day of deliverance for my people,
and many of them shall praise my name, and tell of my wondrous works,
and what I have done for them,
that others may be encouraged to be faithful the residue of their days;
for I have seen many bemoaning themselves in desolation,
and bewailing their lost condition.
Many have been made desolate, by the cruelty of the wicked one;
and they have mourned unto me, and I have seen the bemoaning of my people;
I have seen the travail of the faithful for the unfaithful:
and for the cries of the poor, and the sighings of the needy, will I arise,
and I will work a way for the deliverance of my people;
for the time is near that the prison shall not enclose them, but they shall come forth,
and declare my wondrous works; for I will work, and none shall be able to hinder.`"

This was the glad tidings that lived with me night and day in the time of my confinement.
It was a great satisfaction to my travailing soul--it answered the very
petition I had put up in the night season to the living God;
everlasting honour, glory and renown be given unto him that liveth forevermore,
saith my soul.
For surely I cannot but admire the wonderful lovingkindness,
mercies and favours of the Lord our God, the high and holy one who inhabits eternity,
in condescending to the poor, and to the low, and the little.
He hath revealed his secrets to many who have not thought
themselves worthy to be made partakers of so great a benefit;
but their greatest concern hath been for the redemption
of their souls from under Satan`'s power.
Now, Lord, preserve me in thy fear forever, and keep me from sinning against thee,
that my soul may not go into captivity again.

This was part of the exercise during the time of my confinement with my husband,
and many more of the servants of the most high God, in Ivelchester jail.
When I came out of the prison, to go to the sessions held at Brewton,
I assuredly believed that the time was near that
the prison should not enclose us any longer,
though it was altogether unlikely;
for our persecutors were exceedingly wicked against us.
Although the priest was taken off in a remarkable manner,
many remained who were very cruel, and acted unjustly against us;
and put by the jury that were chosen of our neighbours,
and called another jury presently in the court,
such as they thought most fit for their turn.
Then the clerk began, and read an indictment, viz.: "`That we were found,
or taken at an unlawful assembly, with force of arms,
in contempt of the king and his laws, crown and dignity,
to the terror of the people,`" etc.
And he said to the jury, "`Gentlemen, you have heard their indictment,
if you find them guilty, you find for the king.`"
And a bishop who sat upon the bench with the judge, stood up and said,
"`That the first Quaker that ever was in England,
was hanged for being concerned in the Popish plot.`"
I answered, that the first who was called a Quaker, was now alive.
He said again,
"`He could prove by sufficient witness that he was
hanged for being one in the Popish plot.`"
Then the bishop being enraged, because he was contradicted, held up his hand towards us,
and bid us "`Have a care what we said, for those who had estates amongst us,
it should cost them their estates,
and they that had not should lie in prison until they perished.`"

Such was their rage and wickedness against us, that it was very grievous to hear them;
but there was a secret cry many times ran through my heart unto the Lord, "`Lord,
work for thy name sake, and confound their wisdom, and rage,
and bring down their proud and wicked spirits,
and bring to naught their mischievous contrivance,
that they have been contriving against thy innocent people,
as they have been making themselves merry, and drinking wine to the full,
and feeding themselves with the fatness of the earth, as Dives did,
and have what their hearts lust after,
and yet none of all these things will give them content nor satisfaction,
but the destruction of a poor despised people.
Oh Lord! make thy power known this day, and that which will make most for thy honour,
and the prosperity of thy blessed truth, do thou bring to pass;
that it may be known there is a God in heaven who
can rule the hearts of the children of men;
and whom all men ought to fear, honour and obey.`"

And the Lord was pleased to hear the prayers of his children,
and to answer their request in the days of affliction; for this jury, whom they chose,
as they thought, most fit for the work, were long absent;
but when they came in with their verdict, the foreman could not readily speak,
but looked much like a dead man.
Then the bishop in a rage, asked him, "`Whether we were guilty or not guilty?`"
he answered, "`Guilty of not going to church, but not of a riot.`"
"`Of not going to church,`" said the bishop, "`that is not the matter in hand,
guilty of a riot you mean.`"
Then the rest of the jury said, "`No, my lord, guilty of not going to church,
but not of a riot.`"
"`You mean of an unlawful assembly then.`"
"`Yes,`" said the foreman; "`Why that is a riot in law,`" said the bishop.
Then I answered,
"`We are no rioters:`" then the cryer of the court shook his white rod over my head,
and said, "`Be silent.`"
I said, "`No, we may not be silent, we are a sober people,
and live a good life and conversation; we do unto all men, as we would be done by:
I never wronged man, woman, nor child, and I know none that have aught against us,
unless for the answer of a good conscience;
here are of our neighbours who can testify for us.`"
The cryer continued shaking his white rod over my head, crying, "`Hush, and be silent.`"
Then one of the justices, a sober ancient man, said, "`Let the woman speak for herself,
she speaketh truth and reason, let more of them speak; you are many against them,
and if they may not be suffered to speak for themselves, it is very hard.`"
This a little stopped the rage of the bishop and judge;
then they called to our keeper to take us away,
and to bring us when they called for us again; so they went to their dinner,
and we with our keeper.

But no sooner were they gone, but a great concern fell upon me to follow them;
I could neither eat nor drink, but was pressed in my spirit to go after them;
and when I came, they were sitting down to their dinner,
with a noise of music playing at the going up of their dishes,
which were very many of the choicest things.
I went in amongst them whilst they were at dinner, but I did not see a fit opportunity,
but waited till they had dined: and as they were rising,
I came in with a great dread and awe over my spirit.
One of the great men came to me, and said, "`Good woman, who would you speak withal?`"
I said, "`the judge of the sessions:`" he said, "`I am the judge,
if you have anything to say, I am ready to hear you.`"
But he not being the man who sat upon the bench that day, I said,
"`Thou art not the man I am going to.`"
Then he turned towards the judge who sat that day, and said,
"`This woman has something to say to you.`"
Then one of the justices laid his hand upon my shoulder, and said,
"`Let this good woman have what she will to say, we will hear her.`"

But I getting near to the judge and bishop, who sat at the upper end of the table, said,
"`Forasmuch as you are all here, who sat in judgment against us this day,
I have a concern upon my spirit in vindication of our innocency:
we are well known amongst our neighbours to be a sober and an honest people,
who live a good life and conversation; we do no wrong to any,
we can do good to them that hate us, and pray for them that despitefully use us.
I know of none who has aught against us, but concerning the law of our God.
Notwithstanding all this, we are numbered amongst transgressors,
and have been turned into the common jail amongst felons,
our trades and families are liable to be ruined,
and all these things shall not befall us, but you shall understand thereof;
for I am here this day to testify the truth of it;
for which the just and righteous God will one day plead:
and as sure as the day gives its light,
and the covenant of the day and night cannot be broken, there is not a man here,
nor any that draw breath in the open air,
that shall escape the tribunal seat of God`'s divine justice;
every one shall receive a sentence of just recompense
of reward for their deeds done in their life time,
whether they be good or evil.`"

I can truly say, the dread of the Lord was upon me, insomuch that they were smitten,
and paleness appeared in their faces, and they had not a word to say.
But when I was going forth, some hectoring young man said,
"`I thought it would be so when this woman came in.
I thought she would preach when the spirit moved her;
but why would you suffer her,`" said he to the man of the house,
"`to disturb your guests?`"
Then he said, "`Get you downstairs, or I will throw you down.`"
I turned in again, and said, "`What wrong have I done to any one here,
if I could have kept my conscience clear in staying away, I had not been here this day;
but whether you will hear or forbear,
I shall be clear in the day of account of all your blood.`"
So I left them, and returned to my place, and had great peace with the Lord.
We were not called into court any more that day; but the morrow morning early,
we were called, in order to finish our trial, but the bishop came no more into the court,
that we saw; and the judge was very moderate: a great change indeed!
He only called to the keeper to bring up the Quakers, and called some of us by name,
and said, "`You who stand here indicted,
the court fines you five shillings apiece;`" and
never spake a word of payment of the money,
but broke up the court, their business being done, and went their way,
and our keeper also left us, to our great admiration; above fourscore prisoners,
who were before them that day, were freed.

After dinner, the cryer came in amongst us, and said, "`Neighbours and friends,
I am glad for your release; you are the people of God: men would ruin you,
but God will not suffer them so to do.`"
And said, "`Where is the woman?`"
I said, "`Here am I,`" he replied, "`The Lord bless you, I pray you forgive me,
for I intended no harm, nor would do anything against you;
though I shook my rod over your head, I did it in no evil towards you,
so I hope my honest neighbours and friends, you will forgive me.`"
We answered, "`Yes, freely;`" and desired his well-being forever.
He went his way in much love, praying God to bless us,
and we returned to our habitations, with the peace of the Lord in our bosoms;
everlasting praises be given unto the Lord our God forevermore.

Now my children, the end of my leaving this to you and all, upon record, is,
that future ages may know that the great God of heaven and earth,
who brought up the children of Israel out of Egypt`'s bondage,
who made the water stand on heaps, and brought his children through on dry land,
and overturned Pharaoh and all his host, is our God, in whom we believe,
and his power is not lessened, that he cannot save, nor his arm shortened,
that it cannot deliver, at this day, as in former days; praises to his name forever.

This, my dear children, you know is certainly true,
and you should keep in remembrance these and all other mercies
that the Lord our God hath bestowed upon us,
ever since he gathered us to be a people, which is eight and thirty years ago.
I was in the nineteenth year of my age,
when John Camm and John Audland came first to Bristol,
in the power of the great God of heaven and earth;
and I am a living witness that his presence was with them,
and made their ministry so dreadful, that it pierced the hearts of many.
Oh, the terror that seized my heart, at the sound of John Audland`'s voice,
and the sight of him, before I rightly understood what he said.
But before the meeting was over, the spirit of the Lord moved in my heart,
and I came to see my deplorable state, which made me cry to God for mercy;
a day never to be forgotten by me.
And now I have arrived to the seven and fiftieth year of my age,
oh! the many deliverances, both inward and outward,
which I have been made a living witness of.
The decrees that have been sealed against us,
the threatenings of ruin and destruction which have been sounded in our ears,
how have we been as it were killed all the day long,
and counted as sheep for the slaughter; and yet behold we are alive to this day,
to praise the Lord.
How have the enemies roared, both inwardly and outwardly,
and come with open mouth to devour at once!
And how hath our God helped us?
The great God of heaven and earth hath been our strength in a needful time;
and hath sustained his people and borne up our heads above the waters,
that they have not drowned nor overturned us to this day
everlasting honour be given unto the Lord forever.
But our enemies hath he overturned, and broken their bands asunder,
and hath made them to bow under his dreadful power,
and hath taken many off in his displeasure.
What shall I say in the behalf of all his wondrous works, that mine eyes have seen;
but more especially the inward work of regeneration!
My tongue is not able to demonstrate the tenth part,
that the Lord hath been pleased to bring me through.
Oh! what shall I say at the remembrance of them,
which at this time is livingly come up before me; but bow before the Lord,
and prize his mercies forevermore.

Dear children, keep faithful to the Lord, and his blessed truth,
in which you have been trained up, and your eyes shall see for yourselves,
as mine have for myself.
Be faithful to the spirit of Christ Jesus in your own bosoms,
and do not overlook little things, for they that are not faithful in a little,
shall never be made rulers over much.
Do not exercise yourselves in any matter too high for you,
but mind the Spirit of Truth in your own hearts,
and hearken diligently to the voice of the Lord, that your souls may live.
Keep the Lord always in your remembrance, that you sin not against him;
remember to keep to the daily cross, which will crucify all the motions of the flesh,
and keep you alive to God, and near unto him.
In so doing, you will know his counsel; and seek the kingdom of heaven,
and the righteousness thereof, above all things in this world,
and other things shall be added unto you;
for I will assure you this is the way that my soul hath travailed in,
and hath found favour with God.
One thing more which I have experienced, hath been of moment to me,
that in all my afflictions, and pain and sorrow of body or mind,
I have not had an eye to confide in man, but have applied my heart to the Lord,
and have poured forth my soul unto him.
Oh! thou Physician of value, that can cure both soul and body;
thou that knowest better how to administer to my necessity, than I can ask of thee;
from thee alone do I look for comfort, for there is none besides thee,
that can administer true comfort to me.
And the Lord in due time, hath appeared to my satisfaction, established my goings,
and kept my feet from falling and my heart from going astray, unto this very day;
everlasting honour be given unto his name forevermore.
Amen.

Since I have seen the good effects of my labour and travail,
I earnestly beg of the Lord night and day, to do for you, as he hath done for me.
How have my prayers ascended unto the Lord in public and in private,
and when my hand hath been at labour, and on the highway side.
Oh! my children, let it not be in vain, for I can truly say,
that you are children for whom many prayers have been offered.

Therefore consider it, when I am gone and can no longer watch over you,
for my time is much over; I shall be gone, and see you no more in this world,
nor take care for you, nor give counsel:
therefore have I written this account of part of my travel out of Egypt`'s bondage,
towards the land of rest and peace; which has been through great difficulties,
and through many a sore combat with the enemy of my soul`'s peace, many a fiery trial,
and through a vale of tears.
But do not be discouraged at it,
for you know how wonderfully the great God of heaven
and earth hath been my support in time of need,
and hath borne up my spirit, and given me more strength than I could have believed,
if it had been declared unto me.
How many professors of truth at this day, are going on at an easy rate, careless,
indifferent, slighting the cross, and little concerned for their soul`'s good,
slighting the testimonies of truth,
and spending their precious time which God hath put into their hands,
as if heaven`'s glory and a state of eternity were not worth looking after;
and as if there was no God to punish for these things, nor any day of account.
The consideration of these things hath been weighty upon my spirit for many months,
and morning and evening hath my heart been afflicted, saying within myself,
"`Lord what will become of such, I fear the visitation of many of them is almost over.
Oh! how does my soul lament for them; and I have the greater concern upon my spirit,
to intercede with the Lord to preserve me and mine forever.
Lord, my heart is bowed at this time in the sense of thy love,
the mercies and blessings which thou hast bestowed upon me;
and in consideration of this thy great love, how doth my soul love the Lord,
and desire forevermore to obey his voice, and keep covenant, and abide with him forever;
that I may be kept faithful all my days.

"`And, now oh Lord my God seeing thou hast been pleased thus to deal with me,
and to have regard to the low estate of thy handmaid,
and hast heard my prayers many a time, if I have found favour in thy sight,
once more hear my petition and grant my request.
Bless my children, by preserving them in thy fear, cause them to remember thy mercies,
from day to day; what thou hast done for them, and their father and mother,
in their great affliction, when destruction and ruin were determined against us,
and when we were almost past hope; how hast thou appeared,
and confounded our enemies before our eyes!
Lord, let these things never be forgotten by me, nor them,
whilst we have a day to live upon the earth: but,
sanctify all thy blessings and mercies bestowed upon us, and give us a thankful heart,
and humble mind, and more and more unite us unto thee,
and cause us to walk worthy of the same.
Oh! that my heart was but worthy enough;
for methinks it is not able to set forth thy praises.
No, surely it is impossible for tongue to declare thy infinite goodness,
and thy noble acts.

"`But, Lord, we who have made our choice of thee,
and have believed in thy Son Christ Jesus,
have known him to be sufficient strength in time of need;
and thy holy arm to be made bare, for our deliverance out of thraldom,
have known it sufficient to preserve us to this very day.
Therefore, strengthen my faith, hope and confidence,
that I may steadfastly believe that thou wilt preserve my children,
when I am gone to my resting place.
Lord, keep my family and thy people, let not one of them be lost,
or become a prey to the wicked one.
If thou shouldest yet add more days to my life, let me not cease to pray for them,
and their offspring,
that I may do my endeavour for their entrance into thy blessed kingdom,
so shall I go to my grave in peace.
And now, I do wholly resign them into thy hands,
knowing thou art able to keep them through faith, and to preserve them all their days,
and to do more for them than I am able to ask of thee.
Whatever exercise they meet with, strengthen them, and bear up their spirits,
that they may not be overcome with the temptations of the wicked one: for,
thy power hath been sufficient to redeem my soul.
Lord, once more do I commit the keeping of my spirit to thee, with my children,
and all thy flock and family upon the face of the earth,
with whom my soul is at peace and in unity.
I feel the renewings of thy love at this time,
which is the greatest comfort that can be enjoyed; therefore does my heart,
and all that is within me, return unto thee all praises, glory and honour,
with hearty thanksgiving, and pure obedience forevermore.
Lord, accept it this evening, as a sacrifice from a broken heart, and a contrite spirit,
which thou never rejected: for thou art worthy of it, from this time forth, forever,
and forevermore, Amen.`"

[.signed-section-closing]
This was finished the 13th day of the second month, 1692. By me,

[.signed-section-signature]
Elizabeth Stirredge, Sen.

[.asterism]
'''

The last fourteen years of her life, she lived at Hempstead, in Hertfordshire,
whither her husband removed from Chew-magna, in the county of Somerset, in the year 1688.
She did not travel much abroad in her latter days; except once or twice to Bristol, etc.,
and usually to the Yearly Meeting at London, once a year; but laboured mostly about home,
as she grew aged and weakly; but often as the Lord afforded her strength,
visited the neighbouring meetings in the same county;
and her service therein tended to edify and comfort God`'s heritage,
as many faithful Friends in those parts can bear witness.
And great was her concern for the meeting she belonged to,
which she frequented so long as she was able;
many times going to it through great weakness, and many living and powerful testimonies,
especially towards her latter end, she bore in it, exhorting Friends to faithfulness;
frequently setting forth the wonderful power that attended Friends in the beginning,
and which still doth all the faithful,
of which she often spoke in the beginning of her last illness, amongst her own family.
She departed this life, in peace with the Lord, at Hempstead,
on the 7th day of the ninth month, 1706, in the seventy-second year of her age.

[.asterism]
'''

[.blurb]
=== A Salutation of my Endeared Love, in God`'s Holy Fear, for the Clearing of my Conscience, Once More unto You of the City of Bristol, Amongst whom my Soul hath Travailed Under many Exercises, which have Made my Heart to Tremble Before the Great God of Heaven and Earth, Who will yet Further Reveal His Notable Day, Wherein All Flesh shall Tremble Before Him.

In the sense of the great love of God that hath been
extended unto you of that city continually;
first, in sending his servants amongst you, and enduing them with power from on high,
so that it wrought effectually upon many;
whereby they were brought out of Egypt`'s darkness, and through the Red Sea, spiritually,
and could sing to the Lord, as Moses and the children of Israel did,
when the Lord had wrought wonderfully for their deliverance,
and by a high hand and a wonderful power brought them forth.
Blessed be the Lord God Almighty, and honoured be his worthy name,
and the right arm of his strength there are many
living witnesses of these things in this our day.
Oh, dear Friends! forget it not,
but dwell low in the sense of the deplorable state you were in,
when first the Lord reached unto you, and opened that eye in you,
which let you see you were undone forever,
if the Lord did not arise for your deliverance, when many cried out, "`A Saviour,
or I perish forever.`"
O Friends! what was too dear for us to part with in that day for the Lord?
Truly can my soul say, "`That all that ever my eyes beheld,
was nothing to me in comparison to my soul`'s redemption.`"
It was precious in my eye,
and to this very day the living remembrance of it dwells fresh upon my spirit,
and my soul loveth the Lord, and blesseth his worthy name.
And now the Lord is remembering the covenant that
many made with him in the days of their distress.
Oh! remember, remember to pay your vows to the Lord; and look into your hearts this day,
and with the light of the Lord search and see,
whether you are in covenant with the Lord, or no?
If you are, surely you are not to serve yourselves, but the living God,
who made you for a purpose of his own glory, and redeemed you with his precious blood.

And now consider, you that are at ease in your Zion, and eating and drinking,
and wearing what seemeth desirable in your own eyes,
notwithstanding the honour of the Lord lies engaged, and your souls in great danger,
and the servants of the Lord distressed on your behalf.
Oh! for the Lord`'s sake, and for your own souls`' sake, which will perish,
if you do not speedily repent, arise and strip yourselves,
and shake yourselves from these things and come away, while the call of the Lord lasteth.
Oh! linger not, for the day of the Lord hasteneth,
let nothing hinder you--make no excuses any longer,
lest you be excluded out of God`'s kingdom, and the door be shut against you.
Think upon it, before the midnight cry come,
wherein not one day more will be afforded to work for the Lord.
Then neither wife nor children, lands nor livings, husband nor trade,
gold nor silver will redeem the soul;
then that doleful sentence will be sounded against the rebellious,
"`Depart ye workers of iniquity, into everlasting fire,
prepared for the devil and his angels.`"

The sense of these things lies very heavy upon my spirit,
and bows my heart in reverence before the Lord,
and morning and evening is my heart afflicted, insomuch that I can say,
as the prophet said, "`Oh! that my head were as water,
and mine eyes as a fountain of tears, that I might weep day and night,
for the unfaithful, that my spirit might be eased.`"
For truly, Friends, though I am the least amongst many thousands of the Lord`'s people,
and a weak instrument, yet my soul is concerned,
and my prayers to the great God of heaven and earth are,
"`That he would be pleased again to arise, and utter his voice,
and thunder his alarm from his holy habitation,
and make the hearts of people to tremble before his power,
and that he will yet afford a day and try them again,
and that his trumpet may sound an alarm,
to the awakening of their consciences out of that spiritual slumber,
wherein many are sleeping, and dreaming it is well with them, and that they are rich,
and fat, and full, and need nothing; when their state is miserable, and wretched,
naked and bare, and undone forever, if they do not speedily repent,
and return with their whole hearts, and cry to God for mercy,
and that he will pardon their iniquities, and heal their backslidings.`"

Oh, backsliding Israel! return, return, before it be too late,
for the Lord hath long borne with thee.
Oh, thou city of Bristol! as the testimony livingly sprung in
my heart a little before thy distress came upon thee,
I was constrained to say, "`Oh! thou city of Bristol,
a city of the mercies of the living God, he hath highly favoured thee;
thou hast had a day,
wherein thou mightest have enriched thyself with the treasures of God`'s kingdom,
and have grown strong in the Lord, and in the power of his might,
whereby thou mightest have stood in a living testimony for the Lord, with one consent,
as one man; but now behold, the days of thy distress are at hand,
and thy calamity hastens like an armed man; and who can bemoan thee,
or who can intercede with the Lord for thee?
Who can say to the Lord, Why hast thou suffered these things to come to pass?
Because it is in his justice he hath done it.
And blessed be his name forever, he is fulfilling the prophecies of his servants,
whom he hath sent early and late to proclaim his dreadful day in this city;
and year after year,
and month after month have the mind and will of the Lord been declared,
and messenger after messenger sent,
insomuch that many a full stomach loathed the honey-comb,
and all who seemed to receive it, made not a right use of it; for the Lord`'s end,
in sending his servants in days past, was, that his people might be fitted and prepared,
that judgment or destruction should not come upon his children at unawares;
but that they should believe the testimonies of his truth, and take warning by it,
and amend their lives, and be bowed in spirit,
and humbled before the great God of heaven and earth,
that your prayers in this state might ascend unto the long provoked God,
whose anger is waxen hot, and nothing will appease it but true repentance,
and that with speed, and true brokenness of heart.

Oh! is this your state?
Or are you this day trampling upon the testimonies of truth,
and upon the sufferings of your dear brethren and sisters,
who are sufferers for the testimony of Jesus, and are cruelly used?
Oh! can you forget these things?
Come, put your hands to the work, and your shoulders to the burden,
and cry mightily unto the Lord to spare,
and give a little time to renew your strength in him,
that you may do something for the Lord, though but at the last hour.
Surely Friends, the last hour to many is very near, and the long invited,
if they miss of 4his hour, will never have another hour to work for the living God;
and therefore is my heart pained within me, and the shortness of time is much before me;
and I beg of you, that you will lay it to heart, before it be too late,
and consider how soon the Lord can call for your breath.
Our lives are likened to the flower of the field, as the Lord said to his prophet,
when he said, "`What shall I cry?`"
"`Cry, all flesh is grass, and the glory thereof as the flower of the field.`"
Pray consider, how soon is that withered, and the beauty of it come to naught?
And seeing it is so, why will people run the hazard of their poor souls,
for that which will augment their misery, world without end.

I am very earnest with the Lord, and my heart is pained within me on your behalf;
who should have been as "`pillars in the house of the Lord,`"
that the weakest might have leaned upon you,
that your courage and valour might have appeared in the sight of the weak,
that they might have been encouraged by it.
Thus the strong and the weak might have gone up together
to the mountain of the house of the Lord,
where the Lord would have taught you of his ways, and you might have walked in his paths,
and he would have fortified you with courage, strength and valour,
so that you would have grown strong in the Lord, and in the power of his might,
had you wholly given up yourselves, and all that he had given you,
and gave way to that noble spirit that was in Joshua and Caleb,
who were resolved to follow the Lord, they and their families.
Oh, friends!
I can hardly write what ariseth in my heart, touching this matter;
but in the fear of the Lord, I have this to say,
your eyes should have seen the wonders of the Lord, in a miraculous manner,
as they did who thus leaned upon the Lord, and trusted in his strength,
and believed in him, and then all things were possible;
for by obeying the command of the Lord, the walls of Jericho fell;
but if they had reasoned with flesh and blood, or thought the instruments too mean,
they had never seen the power of the Lord to do this work, neither shall any now,
who reason with flesh and blood.
No, first learn obedience, give up to obey the Lord,
and then your eyes shall see the blessed work of the Lord fulfilled in its due time;
for he is God Almighty, and all-sufficient:
therefore let every heart confide in his power.

Dear friends, keep you heart with all diligence, for out of it are the issues of life;
for we all well know, that the people who live most chaste, keep nearest to the Lord,
and they that are nearest, hear most of his counsel.
And truly friends, the time is at hand,
when all shall he distressed for the Lord`'s will,
and the most faithful cannot spare of the heavenly oil,
then it will be too late for any to go to buy.
Oh! it often riseth in my heart, that yet a little while,
and time to many will be no more, for which my soul is more concerned,
than for any outward suffering; for it is in my heart to believe,
that the great God of heaven and, earth, who hath been long provoked,
and shaken his rod over this nation many times, and nothing will prevail,
will arise in his strength, and go through this nation,
and afflict the inhabitants thereof; he will bring terror and amazement upon them,
that none shall be able to deliver out of his hand; for he hath long called,
and they have not regarded; he hath long held out his hand,
and they have not laid it to heart, and therefore will their calamity come at unawares;
and because they have not regarded the call of the Lord, when they cry aloud to him,
he will not regard them.
Oh! then blessed eternally, and happy forevermore will all those be,
who have obeyed the Lord in their day, and have not their portion with the wicked.
With my endeared love to you, desiring and praying for your soul`'s prosperity,

[.signed-section-closing]
I remain your loving friend,

[.signed-section-signature]
Elizabeth Stirredge.

[.signed-section-context-close]
The 2nd day of the First month, 1683.
