== Testimonies Concerning Elizabeth Stirredge

[.blurb]
=== A Testimony from several Friends belonging to the meeting at Hemel, Hemstead, and the parts adjacent, in the county of Hertford, concerning Elizabeth Stirredge, the 8th of the Third month, 1711.

Our dear friends James and Elizabeth Stirredge, came here to reside about the year 1688,
whose coming into these parts was seasonable,
and we believe ordered by the good providence of God.
It had a tendency to the strength and edification of Friends;
for about that time some were busy to weaken love among brethren,
under specious pretenses of liberty, etc.
But the said Elizabeth being gifted for the ministry,
and acquainted with the wiles and subtle devices of the enemy,
was made a serviceable instrument in our defense and preservation;
being attended with power, wisdom,
and true zeal for the prosperity of the truth and people of God.
She was sound and savory in her doctrine and public ministry,
and tender and affectionate in Christian advice and counsel,
to the comfort of the afflicted and exercised in spirit, declaring,
that the way to the kingdom of God is through tribulation,
agreeably to the ancient account we read in holy Scripture.
And she frequently pressed Friends to sincerity and uprightness of heart.
Although the Lord had given her a large gift, and a good utterance,
she was not forward to appear in public service,
but as an immediate concern came upon her.
She was a good example in frequenting meetings, both on first and weekdays,
and was often made instrumental to stir up the pure minds of many, by way of remembrance,
to our mutual comfort, by her fresh and living testimony.

Her husband also, who departed this life some time since her decease,
was an honest zealous Friend, and her fellow-helper in the work of the Lord,
in his proper gift, and our true friend and brother;
and they were both very near and acceptable to Friends, here and here-away.
But what shall we say? The Lord has called them to his rest in a good old age;
we earnestly desire, as they frequently did,
that the young generation may come up in faithfulness, and fill up the room of all such,
being thereunto spirited by the Lord, that his name may be more and more known,
and glorified to all succeeding generations;--Amen.

Our said friend, Elizabeth Stirredge, departed this life at Hemstead aforesaid,
on the 7th of the ninth month, 1706,
and was buried in Friends' burying-ground at Wood-end, in the said parish.

[.signed-section-signature]
John Edmonds, Michael Turpin, Moses West, Michael Turpin, Jr. Edmond Neale, James Stirredge

[.blurb]
=== John Thornton's account of his neighbor, Elizabeth Stirredge.

I had an intimate acquaintance with her;
and as the Lord had given her a measure of the holy Spirit,
to lead her in the way of peace, he also gave her a public testimony,
in which she was very serviceable in our meetings; being attended with power,
wisdom and true zeal.
Her testimony was sound and savory, to the comforting of the upright-hearted;
she being many times drawn forth to encourage the exercised and afflicted in spirit,
and led to declare, that the way to the kingdom of God is through tribulations.
She would frequently press Friends to upright-heartedness, sincerity and integrity;
being also a good example in her conduct.
Although the Lord had given her a large gift, yet she was backward to appear therein,
except she found it was immediately required of her.
She was zealously concerned against that spirit that led into separation,
and against deceit and hypocrisy,
and had a sharp testimony against such as the great enemy had so misled.
She was a diligent frequenter of meetings, both on first and week-days.
Her husband also being an honest and zealous Friend,
they were both serviceable to truth and Friends.
But the will of God be done; for fully satisfied am I, that they are gone to rest,
and entered into joy and happiness, where all sorrows cease, and tears are wiped away.

[.signed-section-signature]
John Thornton

[.blurb]
=== John Neale's Testimony concerning Elizabeth Stirredge.

It is in my mind to write something as a testimony
concerning my dear and well-beloved friend,
Elizabeth Stirredge, deceased.
She received the truth in the love of it in her young years,
as I have heard from her own mouth, during the time of my acquaintance with her,
which was about fifteen years.
She lived about seven miles from us, and sometimes came to visit our meeting at Watford,
and I with many more were glad to see her,
she being one on whom the Lord was pleased to bestow a gift of the ministry,
that she might tell unto others what God had done for her soul.
My heart has been well affected many times with her testimony,
for she spoke as one having authority, almost to admiration,
considering the weakness of body with which she was afflicted; but the Lord was with her,
who gives strength to the weak, and his power was her support.
It was her lot many times when she came to our meeting, to lodge at my house,
my dear mother, Hannah Neale, and she being very intimate friends,
and heartily loving each others company, which I also loved, for it was pleasant,
and her discourse was edifying to me.
I have been affected to hear her give an account of the sufferings,
which she and many others went through in early days.
When they were going to meeting, they went in peril of their lives,
the wicked and ungodly people throwing stones, clods, and other things at them.
And although many rose up against them,
yet how wonderfully did the Lord preserve his people through many tribulations;
most of which, blessed be the Lord, we in this day are free from.

Much might be said concerning our friend: she was a valiant woman for truth on earth,
a mother in Israel, and a worthy faithful elder in the church of Christ in her time.
And my desire is, that we who are of a younger generation, and are yet left behind,
may in our measure be found treading in the steps of our ancients,
who have served the Lord faithfully in their generation, and are removed from us.
Though our loss of such worthies be great;
yet doubtless they are entered into those mansions of eternal bliss,
where joy unspeakable and full of glory is their portion, for evermore.

[.signed-section-signature]
John Neale.

[.blurb]
=== Concerning her husband, James Stirredge, by the same hand.

He was a man with whom I was well acquainted for many years;
an honest upright-hearted man, one that feared God and eschewed evil;
zealous for the honor of God and for the promotion of his truth on earth;
a hearty lover of faithful Friends, and in his conduct amongst men, blameless.

A zealous man for Monthly and Quarterly Meetings of church government; his desire was,
that Friends in such meetings might so wait upon the Lord, to receive counsel from him,
as to act in the wisdom of God,
that everything contrary to the principles of truth might be kept out of them,
and nothing but truth have the preeminence.

He was a meek-spirited and lowly-minded man,
more in substance than in show.I went to visit him in his last illness,
when he was so weak, that he spoke very low, but very sensible,
and was in a good frame of mind; so that I was refreshed in my visit.

He was very patient under his affliction, and I believe fully resigned to the will of God.
He departed this life in the eighth month, 1708, at Hemstead in Hertfordshire,
and was buried at Friends' burying-ground at Woodend, in the same county.

[.signed-section-signature]
John Neale
