[quote.epigraph, , Prov. 31:30]
____
Charm is deceitful, and beauty is passing, but a woman that fears the Lord,
she shall be praised.
____

== Preface

As the memory of the just is blessed, so there is a justice due to their memories,
who walked in the path of the just, which is as a shining light,
and are the blessed who die in the Lord, who rest from their labors,
and their works follow them to their everlasting reward in the kingdom of heaven;
as well as for the example and admonition of those they leave behind.
This is either by publishing their own memoirs of their lives, when they leave any;
or where that is lacking,
by commemorating them according to the example of holy Scripture.
The following relation of her labors and sufferings for Christ,
written by an early disciple in this Gospel-day,
renders it unnecessary to say much of the author;
her own book being a sufficient memorial of her, and what she was;
only as a necessary introduction to her own account,
I have this to premise concerning her.

I was acquainted with her many jeers, she being my country-woman;
and this testimony lives in my heart concerning her,
that she was a religiously exercised woman, always seeking the best things,
and through the goodness of God, found him whom her soul loved.
She underwent many deep exercises inwardly and outwardly, by contrary spirits,
who opposed the work of the Lord, and his servants and handmaids.
She bore a faithful testimony, as the Lord laid it upon her, and made way for her,
being a true mourner in Zion, for the abominations of the times.
She had a solid savory testimony for the truth, which she received early,
and was faithful and diligent in, according to her gift,
and was well esteemed for her service by the honest-hearted in and about Bristol,
and Chewmagna, in the county of Somerset, and in the countries adjacent,
where her service mostly lay; till she, and her husband and family, removed to Hemstead,
in Hertfordshire, in the year 1688.
She stayed at my house in London, when she came to the Yearly Meeting,
and I was often comforted in her savory testimony,
and to find that the Lord`'s presence was so fresh with her in her latter days.
After several years abode at Hemstead, and labor and service there, she died in the Lord,
in the year 1706, and seventy-second of her age, and is undoubtedly entered into rest.

The following papers written with her own hand, in relation to her labors and sufferings,
were some time since put into my hand to peruse,
as falling mostly within the compass of my knowledge;
especially that part in relation to her imprisonment at Ivelchester,
I being then a prisoner there for the testimony of truth,
in the time of the great imprisonment for attending meetings, in the year 1683.
She was taken at meeting at Chewmagna, with nearly thirty more,
and sent to prison by that wicked persecutor, and under-sheriff of the county,
John Helliar of Bristol, at the instigation of the priest of the parish;
both of whom were soon after cut off by death; the said priest Cross, immediately,
in a very remarkable manner, as is herein related,
and the said Helliar also was smitten with great terror and horror of mind
for the violence he had committed on the people of God in that city,
and kept men to watch with him night and day, for fear the devil would fetch him away;
as I have been credibly informed he expressed.
Another great persecutor there, R. Oliffe, who made much spoil on the said people,
as I heard, cried out he was damned,
and that they should make restitution to them he had wronged,
which he was never able to do; and so both died miserably; and several others.

Such a thrifty trade, says one, is persecution,
that it leaves men never a friend in heaven, or on earth.
Oh, that others would take warning in time by examples of divine vengeance,
to avoid such things, and do no more so wickedly.
For as the righteous shall be had in everlasting remembrance,
so the name of the wicked shall rot; and wherever Helliar`'s name is mentioned it stinks,
as all persecutors do.

I have carefully perused and put in order the following relation;
which I have been comforted in reading, being matter of experience, warning,
exhortation and counsel, written in a good understanding of the things of God,
and the mysteries of his kingdom.
To which is added a short supplement of the last fourteen years of her life;
collected chiefly from her son`'s account; with an epistle to Friends,
and a warning to others, formerly printed;
all which I hope may be of service to her posterity and benefit to others;
and that it will tend to the glory of God, and the comfort and edification of his people;
to whose perusal in much love and sincerity I recommend it, and all to the grace of God,
which is able to build them up,
and give them an inheritance among them that are sanctified;
which is the sincere desire of, reader,

[.signed-section-closing]
Your real friend,

[.signed-section-signature]
John Whiting

[.signed-section-context-close]
London, the 21st of the Second month, 1711
